INSERT INTO bo_booking_product_item
(bo_booking_product_itemid, od_productid, booking_product_item_reference, total_amount_tcy, total_amount_lcy, total_amount_scy, total_commision_amount_tcy, total_commision_amount_lcy, total_commision_amount_scy, currency_code_system, currency_code_local, currency_code_transaction, od_taxid, au_useridins, insertdate, au_useridupd, modifydate, version, dbuserins, dbuserupd, invoice_date, commision_percentage, bo_bookingid, cancel_amount_tcy, od_cxl_policy_ruleid, send_user_notification, product_name, seller_companyid)
VALUES(43, 31, '0061P', 14, 14, 14, 0.56, 0.56, 0.56, 'EUR', 'EUR', 'EUR', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 3566, NULL, NULL, 1, 'Product GMAIL', 553123);
INSERT INTO bo_booking_product_item
(bo_booking_product_itemid, od_productid, booking_product_item_reference, total_amount_tcy, total_amount_lcy, total_amount_scy, total_commision_amount_tcy, total_commision_amount_lcy, total_commision_amount_scy, currency_code_system, currency_code_local, currency_code_transaction, od_taxid, au_useridins, insertdate, au_useridupd, modifydate, version, dbuserins, dbuserupd, invoice_date, commision_percentage, bo_bookingid, cancel_amount_tcy, od_cxl_policy_ruleid, send_user_notification, product_name, seller_companyid)
VALUES(38, 31, '00629', 58, 58, 58, 1.9, 1.9, 1.9, 'EUR', 'EUR', 'EUR', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 3573, 0, NULL, 1, 'Product GMAIL', 553123);
INSERT INTO bo_booking_product_item
(bo_booking_product_itemid, od_productid, booking_product_item_reference, total_amount_tcy, total_amount_lcy, total_amount_scy, total_commision_amount_tcy, total_commision_amount_lcy, total_commision_amount_scy, currency_code_system, currency_code_local, currency_code_transaction, od_taxid, au_useridins, insertdate, au_useridupd, modifydate, version, dbuserins, dbuserupd, invoice_date, commision_percentage, bo_bookingid, cancel_amount_tcy, od_cxl_policy_ruleid, send_user_notification, product_name, seller_companyid)
VALUES(33, 31, '0062K', 28, 28, 28, NULL, NULL, NULL, 'EUR', 'EUR', 'EUR', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 3578, NULL, NULL, 1, 'Product GMAIL', 553123);
INSERT INTO bo_booking_product_item
(bo_booking_product_itemid, od_productid, booking_product_item_reference, total_amount_tcy, total_amount_lcy, total_amount_scy, total_commision_amount_tcy, total_commision_amount_lcy, total_commision_amount_scy, currency_code_system, currency_code_local, currency_code_transaction, od_taxid, au_useridins, insertdate, au_useridupd, modifydate, version, dbuserins, dbuserupd, invoice_date, commision_percentage, bo_bookingid, cancel_amount_tcy, od_cxl_policy_ruleid, send_user_notification, product_name, seller_companyid)
VALUES(30, 31, '0062N', 28, 28, 28, NULL, NULL, NULL, 'EUR', 'EUR', 'EUR', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 3579, NULL, NULL, 1, 'Product GMAIL', 553123);
INSERT INTO bo_booking_product_item
(bo_booking_product_itemid, od_productid, booking_product_item_reference, total_amount_tcy, total_amount_lcy, total_amount_scy, total_commision_amount_tcy, total_commision_amount_lcy, total_commision_amount_scy, currency_code_system, currency_code_local, currency_code_transaction, od_taxid, au_useridins, insertdate, au_useridupd, modifydate, version, dbuserins, dbuserupd, invoice_date, commision_percentage, bo_bookingid, cancel_amount_tcy, od_cxl_policy_ruleid, send_user_notification, product_name, seller_companyid)
VALUES(27, 31, '0062Q', 28, 28, 28, NULL, NULL, NULL, 'EUR', 'EUR', 'EUR', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 3580, NULL, NULL, 1, 'Product GMAIL', 553123);
INSERT INTO bo_booking_product_item
(bo_booking_product_itemid, od_productid, booking_product_item_reference, total_amount_tcy, total_amount_lcy, total_amount_scy, total_commision_amount_tcy, total_commision_amount_lcy, total_commision_amount_scy, currency_code_system, currency_code_local, currency_code_transaction, od_taxid, au_useridins, insertdate, au_useridupd, modifydate, version, dbuserins, dbuserupd, invoice_date, commision_percentage, bo_bookingid, cancel_amount_tcy, od_cxl_policy_ruleid, send_user_notification, product_name, seller_companyid)
VALUES(24, 31, '0062T', 28, 28, 28, NULL, NULL, NULL, 'EUR', 'EUR', 'EUR', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 3581, NULL, NULL, 1, 'Product GMAIL', 553123);
INSERT INTO bo_booking_product_item
(bo_booking_product_itemid, od_productid, booking_product_item_reference, total_amount_tcy, total_amount_lcy, total_amount_scy, total_commision_amount_tcy, total_commision_amount_lcy, total_commision_amount_scy, currency_code_system, currency_code_local, currency_code_transaction, od_taxid, au_useridins, insertdate, au_useridupd, modifydate, version, dbuserins, dbuserupd, invoice_date, commision_percentage, bo_bookingid, cancel_amount_tcy, od_cxl_policy_ruleid, send_user_notification, product_name, seller_companyid)
VALUES(21, 31, '0062W', 28, 28, 28, NULL, NULL, NULL, 'EUR', 'EUR', 'EUR', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 3582, NULL, NULL, 1, 'Product GMAIL', 553123);
INSERT INTO bo_booking_product_item
(bo_booking_product_itemid, od_productid, booking_product_item_reference, total_amount_tcy, total_amount_lcy, total_amount_scy, total_commision_amount_tcy, total_commision_amount_lcy, total_commision_amount_scy, currency_code_system, currency_code_local, currency_code_transaction, od_taxid, au_useridins, insertdate, au_useridupd, modifydate, version, dbuserins, dbuserupd, invoice_date, commision_percentage, bo_bookingid, cancel_amount_tcy, od_cxl_policy_ruleid, send_user_notification, product_name, seller_companyid)
VALUES(18, 31, '0062Z', 28, 28, 28, NULL, NULL, NULL, 'EUR', 'EUR', 'EUR', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 3583, NULL, NULL, 1, 'Product GMAIL', 553123);
INSERT INTO bo_booking_product_item
(bo_booking_product_itemid, od_productid, booking_product_item_reference, total_amount_tcy, total_amount_lcy, total_amount_scy, total_commision_amount_tcy, total_commision_amount_lcy, total_commision_amount_scy, currency_code_system, currency_code_local, currency_code_transaction, od_taxid, au_useridins, insertdate, au_useridupd, modifydate, version, dbuserins, dbuserupd, invoice_date, commision_percentage, bo_bookingid, cancel_amount_tcy, od_cxl_policy_ruleid, send_user_notification, product_name, seller_companyid)
VALUES(15, 31, '00632', 28, 28, 28, NULL, NULL, NULL, 'EUR', 'EUR', 'EUR', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 3584, NULL, NULL, 1, 'Product GMAIL', 553123);
INSERT INTO bo_booking_product_item
(bo_booking_product_itemid, od_productid, booking_product_item_reference, total_amount_tcy, total_amount_lcy, total_amount_scy, total_commision_amount_tcy, total_commision_amount_lcy, total_commision_amount_scy, currency_code_system, currency_code_local, currency_code_transaction, od_taxid, au_useridins, insertdate, au_useridupd, modifydate, version, dbuserins, dbuserupd, invoice_date, commision_percentage, bo_bookingid, cancel_amount_tcy, od_cxl_policy_ruleid, send_user_notification, product_name, seller_companyid)
VALUES(12, 31, '00635', 28, 28, 28, NULL, NULL, NULL, 'EUR', 'EUR', 'EUR', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 3585, NULL, NULL, 1, 'Product GMAIL', 553123);
INSERT INTO bo_booking_product_item
(bo_booking_product_itemid, od_productid, booking_product_item_reference, total_amount_tcy, total_amount_lcy, total_amount_scy, total_commision_amount_tcy, total_commision_amount_lcy, total_commision_amount_scy, currency_code_system, currency_code_local, currency_code_transaction, od_taxid, au_useridins, insertdate, au_useridupd, modifydate, version, dbuserins, dbuserupd, invoice_date, commision_percentage, bo_bookingid, cancel_amount_tcy, od_cxl_policy_ruleid, send_user_notification, product_name, seller_companyid)
VALUES(9, 31, '00638', 28, 28, 28, NULL, NULL, NULL, 'EUR', 'EUR', 'EUR', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 3586, NULL, NULL, 1, 'Product GMAIL', 553123);
INSERT INTO bo_booking_product_item
(bo_booking_product_itemid, od_productid, booking_product_item_reference, total_amount_tcy, total_amount_lcy, total_amount_scy, total_commision_amount_tcy, total_commision_amount_lcy, total_commision_amount_scy, currency_code_system, currency_code_local, currency_code_transaction, od_taxid, au_useridins, insertdate, au_useridupd, modifydate, version, dbuserins, dbuserupd, invoice_date, commision_percentage, bo_bookingid, cancel_amount_tcy, od_cxl_policy_ruleid, send_user_notification, product_name, seller_companyid)
VALUES(6, 31, '0063B', 28, 28, 28, NULL, NULL, NULL, 'EUR', 'EUR', 'EUR', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 3587, NULL, NULL, 1, 'Product GMAIL', 553123);
INSERT INTO bo_booking_product_item
(bo_booking_product_itemid, od_productid, booking_product_item_reference, total_amount_tcy, total_amount_lcy, total_amount_scy, total_commision_amount_tcy, total_commision_amount_lcy, total_commision_amount_scy, currency_code_system, currency_code_local, currency_code_transaction, od_taxid, au_useridins, insertdate, au_useridupd, modifydate, version, dbuserins, dbuserupd, invoice_date, commision_percentage, bo_bookingid, cancel_amount_tcy, od_cxl_policy_ruleid, send_user_notification, product_name, seller_companyid)
VALUES(3, 31, '0063E', 28, 28, 28, NULL, NULL, NULL, 'EUR', 'EUR', 'EUR', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 3588, NULL, NULL, 1, 'Product GMAIL', 553123);
