INSERT INTO triggle.bo_booking_product_item
(bo_booking_product_itemid, od_productid, booking_product_item_reference, total_amount_tcy, total_amount_lcy, total_amount_scy, total_commision_amount_tcy, total_commision_amount_lcy, total_commision_amount_scy, currency_code_system, currency_code_local, currency_code_transaction, od_taxid, au_useridins, insertdate, au_useridupd, modifydate, "version", dbuserins, dbuserupd, invoice_date, commision_percentage, bo_bookingid, cancel_amount_tcy, od_cxl_policy_ruleid, send_user_notification, product_name, seller_companyid)
VALUES(7837, 31, '0061P', 14, 14, 14, 0.56, 0.56, 0.56, 'EUR', 'EUR', 'EUR', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 3566, NULL, NULL, 1, 'Product GMAIL', 553123);
INSERT INTO triggle.bo_booking_product_item
(bo_booking_product_itemid, od_productid, booking_product_item_reference, total_amount_tcy, total_amount_lcy, total_amount_scy, total_commision_amount_tcy, total_commision_amount_lcy, total_commision_amount_scy, currency_code_system, currency_code_local, currency_code_transaction, od_taxid, au_useridins, insertdate, au_useridupd, modifydate, "version", dbuserins, dbuserupd, invoice_date, commision_percentage, bo_bookingid, cancel_amount_tcy, od_cxl_policy_ruleid, send_user_notification, product_name, seller_companyid)
VALUES(7857, 31, '00629', 58, 58, 58, 1.9, 1.9, 1.9, 'EUR', 'EUR', 'EUR', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 3573, 0, NULL, 1, 'Product GMAIL', 553123);
INSERT INTO triggle.bo_booking_product_item
(bo_booking_product_itemid, od_productid, booking_product_item_reference, total_amount_tcy, total_amount_lcy, total_amount_scy, total_commision_amount_tcy, total_commision_amount_lcy, total_commision_amount_scy, currency_code_system, currency_code_local, currency_code_transaction, od_taxid, au_useridins, insertdate, au_useridupd, modifydate, "version", dbuserins, dbuserupd, invoice_date, commision_percentage, bo_bookingid, cancel_amount_tcy, od_cxl_policy_ruleid, send_user_notification, product_name, seller_companyid)
VALUES(7868, 31, '0062K', 28, 28, 28, NULL, NULL, NULL, 'EUR', 'EUR', 'EUR', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 3578, NULL, NULL, 1, 'Product GMAIL', 553123);
INSERT INTO triggle.bo_booking_product_item
(bo_booking_product_itemid, od_productid, booking_product_item_reference, total_amount_tcy, total_amount_lcy, total_amount_scy, total_commision_amount_tcy, total_commision_amount_lcy, total_commision_amount_scy, currency_code_system, currency_code_local, currency_code_transaction, od_taxid, au_useridins, insertdate, au_useridupd, modifydate, "version", dbuserins, dbuserupd, invoice_date, commision_percentage, bo_bookingid, cancel_amount_tcy, od_cxl_policy_ruleid, send_user_notification, product_name, seller_companyid)
VALUES(7871, 31, '0062N', 28, 28, 28, NULL, NULL, NULL, 'EUR', 'EUR', 'EUR', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 3579, NULL, NULL, 1, 'Product GMAIL', 553123);
INSERT INTO triggle.bo_booking_product_item
(bo_booking_product_itemid, od_productid, booking_product_item_reference, total_amount_tcy, total_amount_lcy, total_amount_scy, total_commision_amount_tcy, total_commision_amount_lcy, total_commision_amount_scy, currency_code_system, currency_code_local, currency_code_transaction, od_taxid, au_useridins, insertdate, au_useridupd, modifydate, "version", dbuserins, dbuserupd, invoice_date, commision_percentage, bo_bookingid, cancel_amount_tcy, od_cxl_policy_ruleid, send_user_notification, product_name, seller_companyid)
VALUES(7874, 31, '0062Q', 28, 28, 28, NULL, NULL, NULL, 'EUR', 'EUR', 'EUR', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 3580, NULL, NULL, 1, 'Product GMAIL', 553123);
INSERT INTO triggle.bo_booking_product_item
(bo_booking_product_itemid, od_productid, booking_product_item_reference, total_amount_tcy, total_amount_lcy, total_amount_scy, total_commision_amount_tcy, total_commision_amount_lcy, total_commision_amount_scy, currency_code_system, currency_code_local, currency_code_transaction, od_taxid, au_useridins, insertdate, au_useridupd, modifydate, "version", dbuserins, dbuserupd, invoice_date, commision_percentage, bo_bookingid, cancel_amount_tcy, od_cxl_policy_ruleid, send_user_notification, product_name, seller_companyid)
VALUES(7877, 31, '0062T', 28, 28, 28, NULL, NULL, NULL, 'EUR', 'EUR', 'EUR', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 3581, NULL, NULL, 1, 'Product GMAIL', 553123);
INSERT INTO triggle.bo_booking_product_item
(bo_booking_product_itemid, od_productid, booking_product_item_reference, total_amount_tcy, total_amount_lcy, total_amount_scy, total_commision_amount_tcy, total_commision_amount_lcy, total_commision_amount_scy, currency_code_system, currency_code_local, currency_code_transaction, od_taxid, au_useridins, insertdate, au_useridupd, modifydate, "version", dbuserins, dbuserupd, invoice_date, commision_percentage, bo_bookingid, cancel_amount_tcy, od_cxl_policy_ruleid, send_user_notification, product_name, seller_companyid)
VALUES(7880, 31, '0062W', 28, 28, 28, NULL, NULL, NULL, 'EUR', 'EUR', 'EUR', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 3582, NULL, NULL, 1, 'Product GMAIL', 553123);
INSERT INTO triggle.bo_booking_product_item
(bo_booking_product_itemid, od_productid, booking_product_item_reference, total_amount_tcy, total_amount_lcy, total_amount_scy, total_commision_amount_tcy, total_commision_amount_lcy, total_commision_amount_scy, currency_code_system, currency_code_local, currency_code_transaction, od_taxid, au_useridins, insertdate, au_useridupd, modifydate, "version", dbuserins, dbuserupd, invoice_date, commision_percentage, bo_bookingid, cancel_amount_tcy, od_cxl_policy_ruleid, send_user_notification, product_name, seller_companyid)
VALUES(7883, 31, '0062Z', 28, 28, 28, NULL, NULL, NULL, 'EUR', 'EUR', 'EUR', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 3583, NULL, NULL, 1, 'Product GMAIL', 553123);
INSERT INTO triggle.bo_booking_product_item
(bo_booking_product_itemid, od_productid, booking_product_item_reference, total_amount_tcy, total_amount_lcy, total_amount_scy, total_commision_amount_tcy, total_commision_amount_lcy, total_commision_amount_scy, currency_code_system, currency_code_local, currency_code_transaction, od_taxid, au_useridins, insertdate, au_useridupd, modifydate, "version", dbuserins, dbuserupd, invoice_date, commision_percentage, bo_bookingid, cancel_amount_tcy, od_cxl_policy_ruleid, send_user_notification, product_name, seller_companyid)
VALUES(7886, 31, '00632', 28, 28, 28, NULL, NULL, NULL, 'EUR', 'EUR', 'EUR', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 3584, NULL, NULL, 1, 'Product GMAIL', 553123);
INSERT INTO triggle.bo_booking_product_item
(bo_booking_product_itemid, od_productid, booking_product_item_reference, total_amount_tcy, total_amount_lcy, total_amount_scy, total_commision_amount_tcy, total_commision_amount_lcy, total_commision_amount_scy, currency_code_system, currency_code_local, currency_code_transaction, od_taxid, au_useridins, insertdate, au_useridupd, modifydate, "version", dbuserins, dbuserupd, invoice_date, commision_percentage, bo_bookingid, cancel_amount_tcy, od_cxl_policy_ruleid, send_user_notification, product_name, seller_companyid)
VALUES(7889, 31, '00635', 28, 28, 28, NULL, NULL, NULL, 'EUR', 'EUR', 'EUR', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 3585, NULL, NULL, 1, 'Product GMAIL', 553123);
INSERT INTO triggle.bo_booking_product_item
(bo_booking_product_itemid, od_productid, booking_product_item_reference, total_amount_tcy, total_amount_lcy, total_amount_scy, total_commision_amount_tcy, total_commision_amount_lcy, total_commision_amount_scy, currency_code_system, currency_code_local, currency_code_transaction, od_taxid, au_useridins, insertdate, au_useridupd, modifydate, "version", dbuserins, dbuserupd, invoice_date, commision_percentage, bo_bookingid, cancel_amount_tcy, od_cxl_policy_ruleid, send_user_notification, product_name, seller_companyid)
VALUES(7892, 31, '00638', 28, 28, 28, NULL, NULL, NULL, 'EUR', 'EUR', 'EUR', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 3586, NULL, NULL, 1, 'Product GMAIL', 553123);
INSERT INTO triggle.bo_booking_product_item
(bo_booking_product_itemid, od_productid, booking_product_item_reference, total_amount_tcy, total_amount_lcy, total_amount_scy, total_commision_amount_tcy, total_commision_amount_lcy, total_commision_amount_scy, currency_code_system, currency_code_local, currency_code_transaction, od_taxid, au_useridins, insertdate, au_useridupd, modifydate, "version", dbuserins, dbuserupd, invoice_date, commision_percentage, bo_bookingid, cancel_amount_tcy, od_cxl_policy_ruleid, send_user_notification, product_name, seller_companyid)
VALUES(7895, 31, '0063B', 28, 28, 28, NULL, NULL, NULL, 'EUR', 'EUR', 'EUR', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 3587, NULL, NULL, 1, 'Product GMAIL', 553123);
INSERT INTO triggle.bo_booking_product_item
(bo_booking_product_itemid, od_productid, booking_product_item_reference, total_amount_tcy, total_amount_lcy, total_amount_scy, total_commision_amount_tcy, total_commision_amount_lcy, total_commision_amount_scy, currency_code_system, currency_code_local, currency_code_transaction, od_taxid, au_useridins, insertdate, au_useridupd, modifydate, "version", dbuserins, dbuserupd, invoice_date, commision_percentage, bo_bookingid, cancel_amount_tcy, od_cxl_policy_ruleid, send_user_notification, product_name, seller_companyid)
VALUES(7898, 31, '0063E', 28, 28, 28, NULL, NULL, NULL, 'EUR', 'EUR', 'EUR', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 3588, NULL, NULL, 1, 'Product GMAIL', 553123);
