INSERT INTO bi_billing_item
(bi_billing_itemid, item_type, business_type, bo_bookingid, item_source, invoice_id, document_number, od_companyid, od_vendorid, od_customerid, default_fee, billing_item_amount_tcy, billing_item_amount_lcy, billing_item_amount_scy, invoiced_item_amount_tcy, invoiced_item_amount_lcy, invoiced_item_amount_scy, paid_item_amount_tcy, paid_item_amount_lcy, paid_item_amount_scy, currency_code_transaction, currency_code_local, currency_code_system, gd_status, gd_statusflowtype, au_useridins, insertdate, au_useridupd, modifydate, "version", dbuserins, dbuserupd, bo_booking_itemid, od_feeid)
VALUES(6267, 'INCOME', 'PLATFORM', 3565, 'TRANSACTION_FEE', NULL, NULL, 553199, NULL, 553123, 0, 3, 3, 3, NULL, NULL, NULL, NULL, NULL, NULL, 'EUR', 'EUR', 'EUR', 'OPEN', 'BILLING_ITEM', 50153, '2020-07-24 12:10:53.894', NULL, NULL, NULL, NULL, NULL, 7836, 11);
INSERT INTO bi_billing_item
(bi_billing_itemid, item_type, business_type, bo_bookingid, item_source, invoice_id, document_number, od_companyid, od_vendorid, od_customerid, default_fee, billing_item_amount_tcy, billing_item_amount_lcy, billing_item_amount_scy, invoiced_item_amount_tcy, invoiced_item_amount_lcy, invoiced_item_amount_scy, paid_item_amount_tcy, paid_item_amount_lcy, paid_item_amount_scy, currency_code_transaction, currency_code_local, currency_code_system, gd_status, gd_statusflowtype, au_useridins, insertdate, au_useridupd, modifydate, "version", dbuserins, dbuserupd, bo_booking_itemid, od_feeid)
VALUES(6266, 'COST', 'PLATFORM', 3565, 'TRANSACTION_FEE', NULL, NULL, 553123, 553199, NULL, 0, 3, 3, 3, NULL, NULL, NULL, NULL, NULL, NULL, 'EUR', 'EUR', 'EUR', 'OPEN', 'BILLING_ITEM', 50153, '2020-07-24 12:10:53.798', NULL, NULL, NULL, NULL, NULL, 7836, 11);
INSERT INTO bi_billing_item
(bi_billing_itemid, item_type, business_type, bo_bookingid, item_source, invoice_id, document_number, od_companyid, od_vendorid, od_customerid, default_fee, billing_item_amount_tcy, billing_item_amount_lcy, billing_item_amount_scy, invoiced_item_amount_tcy, invoiced_item_amount_lcy, invoiced_item_amount_scy, paid_item_amount_tcy, paid_item_amount_lcy, paid_item_amount_scy, currency_code_transaction, currency_code_local, currency_code_system, gd_status, gd_statusflowtype, au_useridins, insertdate, au_useridupd, modifydate, "version", dbuserins, dbuserupd, bo_booking_itemid, od_feeid)
VALUES(6272, 'INCOME', 'PURCHASE_SALE', 3566, 'PRODUCT_RATE', NULL, NULL, 553123, NULL, 553200, NULL, 14, 14, 14, NULL, NULL, NULL, NULL, NULL, NULL, 'EUR', 'EUR', 'EUR', 'OPEN', 'BILLING_ITEM', 50153, '2020-07-24 13:00:11.299', NULL, NULL, NULL, NULL, NULL, 7837, NULL);
INSERT INTO bi_billing_item
(bi_billing_itemid, item_type, business_type, bo_bookingid, item_source, invoice_id, document_number, od_companyid, od_vendorid, od_customerid, default_fee, billing_item_amount_tcy, billing_item_amount_lcy, billing_item_amount_scy, invoiced_item_amount_tcy, invoiced_item_amount_lcy, invoiced_item_amount_scy, paid_item_amount_tcy, paid_item_amount_lcy, paid_item_amount_scy, currency_code_transaction, currency_code_local, currency_code_system, gd_status, gd_statusflowtype, au_useridins, insertdate, au_useridupd, modifydate, "version", dbuserins, dbuserupd, bo_booking_itemid, od_feeid)
VALUES(6271, 'INCOME', 'PLATFORM', 3566, 'TRANSACTION_FEE', NULL, NULL, 553199, NULL, 553123, 0, 3, 3, 3, NULL, NULL, NULL, NULL, NULL, NULL, 'EUR', 'EUR', 'EUR', 'OPEN', 'BILLING_ITEM', 50153, '2020-07-24 13:00:10.498', NULL, NULL, NULL, NULL, NULL, 7839, 11);
INSERT INTO bi_billing_item
(bi_billing_itemid, item_type, business_type, bo_bookingid, item_source, invoice_id, document_number, od_companyid, od_vendorid, od_customerid, default_fee, billing_item_amount_tcy, billing_item_amount_lcy, billing_item_amount_scy, invoiced_item_amount_tcy, invoiced_item_amount_lcy, invoiced_item_amount_scy, paid_item_amount_tcy, paid_item_amount_lcy, paid_item_amount_scy, currency_code_transaction, currency_code_local, currency_code_system, gd_status, gd_statusflowtype, au_useridins, insertdate, au_useridupd, modifydate, "version", dbuserins, dbuserupd, bo_booking_itemid, od_feeid)
VALUES(6270, 'COST', 'PLATFORM', 3566, 'TRANSACTION_FEE', NULL, NULL, 553123, 553199, NULL, 0, 3, 3, 3, NULL, NULL, NULL, NULL, NULL, NULL, 'EUR', 'EUR', 'EUR', 'OPEN', 'BILLING_ITEM', 50153, '2020-07-24 13:00:10.433', NULL, NULL, NULL, NULL, NULL, 7839, 11);
INSERT INTO bi_billing_item
(bi_billing_itemid, item_type, business_type, bo_bookingid, item_source, invoice_id, document_number, od_companyid, od_vendorid, od_customerid, default_fee, billing_item_amount_tcy, billing_item_amount_lcy, billing_item_amount_scy, invoiced_item_amount_tcy, invoiced_item_amount_lcy, invoiced_item_amount_scy, paid_item_amount_tcy, paid_item_amount_lcy, paid_item_amount_scy, currency_code_transaction, currency_code_local, currency_code_system, gd_status, gd_statusflowtype, au_useridins, insertdate, au_useridupd, modifydate, "version", dbuserins, dbuserupd, bo_booking_itemid, od_feeid)
VALUES(6280, 'INCOME', 'PURCHASE_SALE', 3573, 'PRODUCT_RATE', NULL, NULL, 553123, NULL, 553200, NULL, 58, 58, 58, NULL, NULL, NULL, NULL, NULL, NULL, 'EUR', 'EUR', 'EUR', 'VOID', 'BILLING_ITEM', 50153, '2020-08-14 09:14:17.645', NULL, NULL, NULL, NULL, NULL, 7857, NULL);
INSERT INTO bi_billing_item
(bi_billing_itemid, item_type, business_type, bo_bookingid, item_source, invoice_id, document_number, od_companyid, od_vendorid, od_customerid, default_fee, billing_item_amount_tcy, billing_item_amount_lcy, billing_item_amount_scy, invoiced_item_amount_tcy, invoiced_item_amount_lcy, invoiced_item_amount_scy, paid_item_amount_tcy, paid_item_amount_lcy, paid_item_amount_scy, currency_code_transaction, currency_code_local, currency_code_system, gd_status, gd_statusflowtype, au_useridins, insertdate, au_useridupd, modifydate, "version", dbuserins, dbuserupd, bo_booking_itemid, od_feeid)
VALUES(6278, 'COST', 'GATEWAY_CARD', 3573, 'GATEWAY_FEE', NULL, NULL, 553199, 558075, NULL, 0, 4, 4, 4, NULL, NULL, NULL, NULL, NULL, NULL, 'EUR', 'EUR', 'EUR', 'OPEN', 'BILLING_ITEM', NULL, '2020-08-12 12:39:45.251', NULL, NULL, NULL, NULL, NULL, 7859, 13);
INSERT INTO bi_billing_item
(bi_billing_itemid, item_type, business_type, bo_bookingid, item_source, invoice_id, document_number, od_companyid, od_vendorid, od_customerid, default_fee, billing_item_amount_tcy, billing_item_amount_lcy, billing_item_amount_scy, invoiced_item_amount_tcy, invoiced_item_amount_lcy, invoiced_item_amount_scy, paid_item_amount_tcy, paid_item_amount_lcy, paid_item_amount_scy, currency_code_transaction, currency_code_local, currency_code_system, gd_status, gd_statusflowtype, au_useridins, insertdate, au_useridupd, modifydate, "version", dbuserins, dbuserupd, bo_booking_itemid, od_feeid)
VALUES(6275, 'COST', 'GATEWAY_CARD', 3573, 'GATEWAY_FEE', NULL, NULL, 553199, 558075, NULL, 0, 0.87, 0.87, 0.87, NULL, NULL, NULL, NULL, NULL, NULL, 'EUR', 'EUR', 'EUR', 'OPEN', 'BILLING_ITEM', NULL, '2020-08-12 12:39:44.147', NULL, NULL, NULL, NULL, NULL, 7859, 14);
INSERT INTO bi_billing_item
(bi_billing_itemid, item_type, business_type, bo_bookingid, item_source, invoice_id, document_number, od_companyid, od_vendorid, od_customerid, default_fee, billing_item_amount_tcy, billing_item_amount_lcy, billing_item_amount_scy, invoiced_item_amount_tcy, invoiced_item_amount_lcy, invoiced_item_amount_scy, paid_item_amount_tcy, paid_item_amount_lcy, paid_item_amount_scy, currency_code_transaction, currency_code_local, currency_code_system, gd_status, gd_statusflowtype, au_useridins, insertdate, au_useridupd, modifydate, "version", dbuserins, dbuserupd, bo_booking_itemid, od_feeid)
VALUES(6281, 'INCOME', 'PLATFORM', 3573, 'PAYMENT_FEE', NULL, NULL, 553199, NULL, 553123, 0, 0.87, 0.87, 0.87, NULL, NULL, NULL, NULL, NULL, NULL, 'EUR', 'EUR', 'EUR', 'OPEN', 'BILLING_ITEM', NULL, '2020-08-12 12:39:46.663', NULL, NULL, NULL, NULL, NULL, 7860, 15);
INSERT INTO bi_billing_item
(bi_billing_itemid, item_type, business_type, bo_bookingid, item_source, invoice_id, document_number, od_companyid, od_vendorid, od_customerid, default_fee, billing_item_amount_tcy, billing_item_amount_lcy, billing_item_amount_scy, invoiced_item_amount_tcy, invoiced_item_amount_lcy, invoiced_item_amount_scy, paid_item_amount_tcy, paid_item_amount_lcy, paid_item_amount_scy, currency_code_transaction, currency_code_local, currency_code_system, gd_status, gd_statusflowtype, au_useridins, insertdate, au_useridupd, modifydate, "version", dbuserins, dbuserupd, bo_booking_itemid, od_feeid)
VALUES(6279, 'COST', 'PLATFORM', 3573, 'PAYMENT_FEE', NULL, NULL, 553123, 553199, NULL, 0, 0.87, 0.87, 0.87, NULL, NULL, NULL, NULL, NULL, NULL, 'EUR', 'EUR', 'EUR', 'OPEN', 'BILLING_ITEM', NULL, '2020-08-12 12:39:45.756', NULL, NULL, NULL, NULL, NULL, 7860, 15);
INSERT INTO bi_billing_item
(bi_billing_itemid, item_type, business_type, bo_bookingid, item_source, invoice_id, document_number, od_companyid, od_vendorid, od_customerid, default_fee, billing_item_amount_tcy, billing_item_amount_lcy, billing_item_amount_scy, invoiced_item_amount_tcy, invoiced_item_amount_lcy, invoiced_item_amount_scy, paid_item_amount_tcy, paid_item_amount_lcy, paid_item_amount_scy, currency_code_transaction, currency_code_local, currency_code_system, gd_status, gd_statusflowtype, au_useridins, insertdate, au_useridupd, modifydate, "version", dbuserins, dbuserupd, bo_booking_itemid, od_feeid)
VALUES(6277, 'COST', 'PLATFORM', 3573, 'TRANSACTION_FEE', NULL, NULL, 553123, 553199, NULL, 0, 9, 9, 9, NULL, NULL, NULL, NULL, NULL, NULL, 'EUR', 'EUR', 'EUR', 'OPEN', 'BILLING_ITEM', NULL, '2020-08-12 12:39:45.155', NULL, NULL, NULL, NULL, NULL, 7861, 11);
INSERT INTO bi_billing_item
(bi_billing_itemid, item_type, business_type, bo_bookingid, item_source, invoice_id, document_number, od_companyid, od_vendorid, od_customerid, default_fee, billing_item_amount_tcy, billing_item_amount_lcy, billing_item_amount_scy, invoiced_item_amount_tcy, invoiced_item_amount_lcy, invoiced_item_amount_scy, paid_item_amount_tcy, paid_item_amount_lcy, paid_item_amount_scy, currency_code_transaction, currency_code_local, currency_code_system, gd_status, gd_statusflowtype, au_useridins, insertdate, au_useridupd, modifydate, "version", dbuserins, dbuserupd, bo_booking_itemid, od_feeid)
VALUES(6276, 'INCOME', 'PLATFORM', 3573, 'TRANSACTION_FEE', NULL, NULL, 553199, NULL, 553123, 0, 9, 9, 9, NULL, NULL, NULL, NULL, NULL, NULL, 'EUR', 'EUR', 'EUR', 'OPEN', 'BILLING_ITEM', NULL, '2020-08-12 12:39:45.145', NULL, NULL, NULL, NULL, NULL, 7861, 11);
INSERT INTO bi_billing_item
(bi_billing_itemid, item_type, business_type, bo_bookingid, item_source, invoice_id, document_number, od_companyid, od_vendorid, od_customerid, default_fee, billing_item_amount_tcy, billing_item_amount_lcy, billing_item_amount_scy, invoiced_item_amount_tcy, invoiced_item_amount_lcy, invoiced_item_amount_scy, paid_item_amount_tcy, paid_item_amount_lcy, paid_item_amount_scy, currency_code_transaction, currency_code_local, currency_code_system, gd_status, gd_statusflowtype, au_useridins, insertdate, au_useridupd, modifydate, "version", dbuserins, dbuserupd, bo_booking_itemid, od_feeid)
VALUES(6298, 'INCOME', 'PURCHASE_SALE', 3578, 'PRODUCT_RATE', NULL, NULL, 553123, NULL, 553200, NULL, 28, 28, 28, NULL, NULL, NULL, NULL, NULL, NULL, 'EUR', 'EUR', 'EUR', 'OPEN', 'BILLING_ITEM', 50153, '2020-08-20 13:01:02.269', NULL, NULL, NULL, NULL, NULL, 7868, NULL);
INSERT INTO bi_billing_item
(bi_billing_itemid, item_type, business_type, bo_bookingid, item_source, invoice_id, document_number, od_companyid, od_vendorid, od_customerid, default_fee, billing_item_amount_tcy, billing_item_amount_lcy, billing_item_amount_scy, invoiced_item_amount_tcy, invoiced_item_amount_lcy, invoiced_item_amount_scy, paid_item_amount_tcy, paid_item_amount_lcy, paid_item_amount_scy, currency_code_transaction, currency_code_local, currency_code_system, gd_status, gd_statusflowtype, au_useridins, insertdate, au_useridupd, modifydate, "version", dbuserins, dbuserupd, bo_booking_itemid, od_feeid)
VALUES(6299, 'INCOME', 'PLATFORM', 3578, 'TRANSACTION_FEE', NULL, NULL, 553199, NULL, 553123, 0, 6, 6, 6, NULL, NULL, NULL, NULL, NULL, NULL, 'EUR', 'EUR', 'EUR', 'OPEN', 'BILLING_ITEM', 50153, '2020-08-20 13:01:02.361', NULL, NULL, NULL, NULL, NULL, 7870, 11);
INSERT INTO bi_billing_item
(bi_billing_itemid, item_type, business_type, bo_bookingid, item_source, invoice_id, document_number, od_companyid, od_vendorid, od_customerid, default_fee, billing_item_amount_tcy, billing_item_amount_lcy, billing_item_amount_scy, invoiced_item_amount_tcy, invoiced_item_amount_lcy, invoiced_item_amount_scy, paid_item_amount_tcy, paid_item_amount_lcy, paid_item_amount_scy, currency_code_transaction, currency_code_local, currency_code_system, gd_status, gd_statusflowtype, au_useridins, insertdate, au_useridupd, modifydate, "version", dbuserins, dbuserupd, bo_booking_itemid, od_feeid)
VALUES(6297, 'COST', 'PLATFORM', 3578, 'TRANSACTION_FEE', NULL, NULL, 553123, 553199, NULL, 0, 6, 6, 6, NULL, NULL, NULL, NULL, NULL, NULL, 'EUR', 'EUR', 'EUR', 'OPEN', 'BILLING_ITEM', 50153, '2020-08-20 13:01:01.464', NULL, NULL, NULL, NULL, NULL, 7870, 11);
INSERT INTO bi_billing_item
(bi_billing_itemid, item_type, business_type, bo_bookingid, item_source, invoice_id, document_number, od_companyid, od_vendorid, od_customerid, default_fee, billing_item_amount_tcy, billing_item_amount_lcy, billing_item_amount_scy, invoiced_item_amount_tcy, invoiced_item_amount_lcy, invoiced_item_amount_scy, paid_item_amount_tcy, paid_item_amount_lcy, paid_item_amount_scy, currency_code_transaction, currency_code_local, currency_code_system, gd_status, gd_statusflowtype, au_useridins, insertdate, au_useridupd, modifydate, "version", dbuserins, dbuserupd, bo_booking_itemid, od_feeid)
VALUES(6295, 'INCOME', 'PURCHASE_SALE', 3579, 'PRODUCT_RATE', NULL, NULL, 553123, NULL, 553200, NULL, 28, 28, 28, NULL, NULL, NULL, NULL, NULL, NULL, 'EUR', 'EUR', 'EUR', 'OPEN', 'BILLING_ITEM', 50153, '2020-08-20 13:00:23.681', NULL, NULL, NULL, NULL, NULL, 7871, NULL);
INSERT INTO bi_billing_item
(bi_billing_itemid, item_type, business_type, bo_bookingid, item_source, invoice_id, document_number, od_companyid, od_vendorid, od_customerid, default_fee, billing_item_amount_tcy, billing_item_amount_lcy, billing_item_amount_scy, invoiced_item_amount_tcy, invoiced_item_amount_lcy, invoiced_item_amount_scy, paid_item_amount_tcy, paid_item_amount_lcy, paid_item_amount_scy, currency_code_transaction, currency_code_local, currency_code_system, gd_status, gd_statusflowtype, au_useridins, insertdate, au_useridupd, modifydate, "version", dbuserins, dbuserupd, bo_booking_itemid, od_feeid)
VALUES(6296, 'INCOME', 'PLATFORM', 3579, 'TRANSACTION_FEE', NULL, NULL, 553199, NULL, 553123, 0, 6, 6, 6, NULL, NULL, NULL, NULL, NULL, NULL, 'EUR', 'EUR', 'EUR', 'OPEN', 'BILLING_ITEM', 50153, '2020-08-20 13:00:23.761', NULL, NULL, NULL, NULL, NULL, 7873, 11);
INSERT INTO bi_billing_item
(bi_billing_itemid, item_type, business_type, bo_bookingid, item_source, invoice_id, document_number, od_companyid, od_vendorid, od_customerid, default_fee, billing_item_amount_tcy, billing_item_amount_lcy, billing_item_amount_scy, invoiced_item_amount_tcy, invoiced_item_amount_lcy, invoiced_item_amount_scy, paid_item_amount_tcy, paid_item_amount_lcy, paid_item_amount_scy, currency_code_transaction, currency_code_local, currency_code_system, gd_status, gd_statusflowtype, au_useridins, insertdate, au_useridupd, modifydate, "version", dbuserins, dbuserupd, bo_booking_itemid, od_feeid)
VALUES(6294, 'COST', 'PLATFORM', 3579, 'TRANSACTION_FEE', NULL, NULL, 553123, 553199, NULL, 0, 6, 6, 6, NULL, NULL, NULL, NULL, NULL, NULL, 'EUR', 'EUR', 'EUR', 'OPEN', 'BILLING_ITEM', 50153, '2020-08-20 13:00:22.668', NULL, NULL, NULL, NULL, NULL, 7873, 11);
INSERT INTO bi_billing_item
(bi_billing_itemid, item_type, business_type, bo_bookingid, item_source, invoice_id, document_number, od_companyid, od_vendorid, od_customerid, default_fee, billing_item_amount_tcy, billing_item_amount_lcy, billing_item_amount_scy, invoiced_item_amount_tcy, invoiced_item_amount_lcy, invoiced_item_amount_scy, paid_item_amount_tcy, paid_item_amount_lcy, paid_item_amount_scy, currency_code_transaction, currency_code_local, currency_code_system, gd_status, gd_statusflowtype, au_useridins, insertdate, au_useridupd, modifydate, "version", dbuserins, dbuserupd, bo_booking_itemid, od_feeid)
VALUES(6283, 'INCOME', 'PURCHASE_SALE', 3580, 'PRODUCT_RATE', NULL, NULL, 553123, NULL, 553200, NULL, 28, 28, 28, NULL, NULL, NULL, NULL, NULL, NULL, 'EUR', 'EUR', 'EUR', 'OPEN', 'BILLING_ITEM', 50153, '2020-08-20 12:44:34.094', NULL, NULL, NULL, NULL, NULL, 7874, NULL);
INSERT INTO bi_billing_item
(bi_billing_itemid, item_type, business_type, bo_bookingid, item_source, invoice_id, document_number, od_companyid, od_vendorid, od_customerid, default_fee, billing_item_amount_tcy, billing_item_amount_lcy, billing_item_amount_scy, invoiced_item_amount_tcy, invoiced_item_amount_lcy, invoiced_item_amount_scy, paid_item_amount_tcy, paid_item_amount_lcy, paid_item_amount_scy, currency_code_transaction, currency_code_local, currency_code_system, gd_status, gd_statusflowtype, au_useridins, insertdate, au_useridupd, modifydate, "version", dbuserins, dbuserupd, bo_booking_itemid, od_feeid)
VALUES(6284, 'COST', 'PLATFORM', 3580, 'TRANSACTION_FEE', NULL, NULL, 553123, 553199, NULL, 0, 6, 6, 6, NULL, NULL, NULL, NULL, NULL, NULL, 'EUR', 'EUR', 'EUR', 'OPEN', 'BILLING_ITEM', 50153, '2020-08-20 12:44:34.226', NULL, NULL, NULL, NULL, NULL, 7876, 11);
INSERT INTO bi_billing_item
(bi_billing_itemid, item_type, business_type, bo_bookingid, item_source, invoice_id, document_number, od_companyid, od_vendorid, od_customerid, default_fee, billing_item_amount_tcy, billing_item_amount_lcy, billing_item_amount_scy, invoiced_item_amount_tcy, invoiced_item_amount_lcy, invoiced_item_amount_scy, paid_item_amount_tcy, paid_item_amount_lcy, paid_item_amount_scy, currency_code_transaction, currency_code_local, currency_code_system, gd_status, gd_statusflowtype, au_useridins, insertdate, au_useridupd, modifydate, "version", dbuserins, dbuserupd, bo_booking_itemid, od_feeid)
VALUES(6282, 'INCOME', 'PLATFORM', 3580, 'TRANSACTION_FEE', NULL, NULL, 553199, NULL, 553123, 0, 6, 6, 6, NULL, NULL, NULL, NULL, NULL, NULL, 'EUR', 'EUR', 'EUR', 'OPEN', 'BILLING_ITEM', 50153, '2020-08-20 12:44:31.296', NULL, NULL, NULL, NULL, NULL, 7876, 11);
INSERT INTO bi_billing_item
(bi_billing_itemid, item_type, business_type, bo_bookingid, item_source, invoice_id, document_number, od_companyid, od_vendorid, od_customerid, default_fee, billing_item_amount_tcy, billing_item_amount_lcy, billing_item_amount_scy, invoiced_item_amount_tcy, invoiced_item_amount_lcy, invoiced_item_amount_scy, paid_item_amount_tcy, paid_item_amount_lcy, paid_item_amount_scy, currency_code_transaction, currency_code_local, currency_code_system, gd_status, gd_statusflowtype, au_useridins, insertdate, au_useridupd, modifydate, "version", dbuserins, dbuserupd, bo_booking_itemid, od_feeid)
VALUES(6287, 'INCOME', 'PURCHASE_SALE', 3581, 'PRODUCT_RATE', NULL, NULL, 553123, NULL, 553200, NULL, 28, 28, 28, NULL, NULL, NULL, NULL, NULL, NULL, 'EUR', 'EUR', 'EUR', 'OPEN', 'BILLING_ITEM', 50153, '2020-08-20 12:45:42.892', NULL, NULL, NULL, NULL, NULL, 7877, NULL);
INSERT INTO bi_billing_item
(bi_billing_itemid, item_type, business_type, bo_bookingid, item_source, invoice_id, document_number, od_companyid, od_vendorid, od_customerid, default_fee, billing_item_amount_tcy, billing_item_amount_lcy, billing_item_amount_scy, invoiced_item_amount_tcy, invoiced_item_amount_lcy, invoiced_item_amount_scy, paid_item_amount_tcy, paid_item_amount_lcy, paid_item_amount_scy, currency_code_transaction, currency_code_local, currency_code_system, gd_status, gd_statusflowtype, au_useridins, insertdate, au_useridupd, modifydate, "version", dbuserins, dbuserupd, bo_booking_itemid, od_feeid)
VALUES(6286, 'COST', 'PLATFORM', 3581, 'TRANSACTION_FEE', NULL, NULL, 553123, 553199, NULL, 0, 6, 6, 6, NULL, NULL, NULL, NULL, NULL, NULL, 'EUR', 'EUR', 'EUR', 'OPEN', 'BILLING_ITEM', 50153, '2020-08-20 12:45:39.897', NULL, NULL, NULL, NULL, NULL, 7879, 11);
INSERT INTO bi_billing_item
(bi_billing_itemid, item_type, business_type, bo_bookingid, item_source, invoice_id, document_number, od_companyid, od_vendorid, od_customerid, default_fee, billing_item_amount_tcy, billing_item_amount_lcy, billing_item_amount_scy, invoiced_item_amount_tcy, invoiced_item_amount_lcy, invoiced_item_amount_scy, paid_item_amount_tcy, paid_item_amount_lcy, paid_item_amount_scy, currency_code_transaction, currency_code_local, currency_code_system, gd_status, gd_statusflowtype, au_useridins, insertdate, au_useridupd, modifydate, "version", dbuserins, dbuserupd, bo_booking_itemid, od_feeid)
VALUES(6285, 'INCOME', 'PLATFORM', 3581, 'TRANSACTION_FEE', NULL, NULL, 553199, NULL, 553123, 0, 6, 6, 6, NULL, NULL, NULL, NULL, NULL, NULL, 'EUR', 'EUR', 'EUR', 'OPEN', 'BILLING_ITEM', 50153, '2020-08-20 12:45:39.768', NULL, NULL, NULL, NULL, NULL, 7879, 11);
INSERT INTO bi_billing_item
(bi_billing_itemid, item_type, business_type, bo_bookingid, item_source, invoice_id, document_number, od_companyid, od_vendorid, od_customerid, default_fee, billing_item_amount_tcy, billing_item_amount_lcy, billing_item_amount_scy, invoiced_item_amount_tcy, invoiced_item_amount_lcy, invoiced_item_amount_scy, paid_item_amount_tcy, paid_item_amount_lcy, paid_item_amount_scy, currency_code_transaction, currency_code_local, currency_code_system, gd_status, gd_statusflowtype, au_useridins, insertdate, au_useridupd, modifydate, "version", dbuserins, dbuserupd, bo_booking_itemid, od_feeid)
VALUES(6289, 'INCOME', 'PURCHASE_SALE', 3582, 'PRODUCT_RATE', NULL, NULL, 553123, NULL, 553200, NULL, 28, 28, 28, NULL, NULL, NULL, NULL, NULL, NULL, 'EUR', 'EUR', 'EUR', 'OPEN', 'BILLING_ITEM', 50153, '2020-08-20 12:48:01.879', NULL, NULL, NULL, NULL, NULL, 7880, NULL);
INSERT INTO bi_billing_item
(bi_billing_itemid, item_type, business_type, bo_bookingid, item_source, invoice_id, document_number, od_companyid, od_vendorid, od_customerid, default_fee, billing_item_amount_tcy, billing_item_amount_lcy, billing_item_amount_scy, invoiced_item_amount_tcy, invoiced_item_amount_lcy, invoiced_item_amount_scy, paid_item_amount_tcy, paid_item_amount_lcy, paid_item_amount_scy, currency_code_transaction, currency_code_local, currency_code_system, gd_status, gd_statusflowtype, au_useridins, insertdate, au_useridupd, modifydate, "version", dbuserins, dbuserupd, bo_booking_itemid, od_feeid)
VALUES(6290, 'INCOME', 'PLATFORM', 3582, 'TRANSACTION_FEE', NULL, NULL, 553199, NULL, 553123, 0, 6, 6, 6, NULL, NULL, NULL, NULL, NULL, NULL, 'EUR', 'EUR', 'EUR', 'OPEN', 'BILLING_ITEM', 50153, '2020-08-20 12:48:02.028', NULL, NULL, NULL, NULL, NULL, 7882, 11);
INSERT INTO bi_billing_item
(bi_billing_itemid, item_type, business_type, bo_bookingid, item_source, invoice_id, document_number, od_companyid, od_vendorid, od_customerid, default_fee, billing_item_amount_tcy, billing_item_amount_lcy, billing_item_amount_scy, invoiced_item_amount_tcy, invoiced_item_amount_lcy, invoiced_item_amount_scy, paid_item_amount_tcy, paid_item_amount_lcy, paid_item_amount_scy, currency_code_transaction, currency_code_local, currency_code_system, gd_status, gd_statusflowtype, au_useridins, insertdate, au_useridupd, modifydate, "version", dbuserins, dbuserupd, bo_booking_itemid, od_feeid)
VALUES(6288, 'COST', 'PLATFORM', 3582, 'TRANSACTION_FEE', NULL, NULL, 553123, 553199, NULL, 0, 6, 6, 6, NULL, NULL, NULL, NULL, NULL, NULL, 'EUR', 'EUR', 'EUR', 'OPEN', 'BILLING_ITEM', 50153, '2020-08-20 12:47:58.951', NULL, NULL, NULL, NULL, NULL, 7882, 11);
INSERT INTO bi_billing_item
(bi_billing_itemid, item_type, business_type, bo_bookingid, item_source, invoice_id, document_number, od_companyid, od_vendorid, od_customerid, default_fee, billing_item_amount_tcy, billing_item_amount_lcy, billing_item_amount_scy, invoiced_item_amount_tcy, invoiced_item_amount_lcy, invoiced_item_amount_scy, paid_item_amount_tcy, paid_item_amount_lcy, paid_item_amount_scy, currency_code_transaction, currency_code_local, currency_code_system, gd_status, gd_statusflowtype, au_useridins, insertdate, au_useridupd, modifydate, "version", dbuserins, dbuserupd, bo_booking_itemid, od_feeid)
VALUES(6293, 'INCOME', 'PURCHASE_SALE', 3583, 'PRODUCT_RATE', NULL, NULL, 553123, NULL, 553200, NULL, 28, 28, 28, NULL, NULL, NULL, NULL, NULL, NULL, 'EUR', 'EUR', 'EUR', 'OPEN', 'BILLING_ITEM', 50153, '2020-08-20 12:53:35.818', NULL, NULL, NULL, NULL, NULL, 7883, NULL);
INSERT INTO bi_billing_item
(bi_billing_itemid, item_type, business_type, bo_bookingid, item_source, invoice_id, document_number, od_companyid, od_vendorid, od_customerid, default_fee, billing_item_amount_tcy, billing_item_amount_lcy, billing_item_amount_scy, invoiced_item_amount_tcy, invoiced_item_amount_lcy, invoiced_item_amount_scy, paid_item_amount_tcy, paid_item_amount_lcy, paid_item_amount_scy, currency_code_transaction, currency_code_local, currency_code_system, gd_status, gd_statusflowtype, au_useridins, insertdate, au_useridupd, modifydate, "version", dbuserins, dbuserupd, bo_booking_itemid, od_feeid)
VALUES(6292, 'COST', 'PLATFORM', 3583, 'TRANSACTION_FEE', NULL, NULL, 553123, 553199, NULL, 0, 6, 6, 6, NULL, NULL, NULL, NULL, NULL, NULL, 'EUR', 'EUR', 'EUR', 'OPEN', 'BILLING_ITEM', 50153, '2020-08-20 12:53:33.048', NULL, NULL, NULL, NULL, NULL, 7885, 11);
INSERT INTO bi_billing_item
(bi_billing_itemid, item_type, business_type, bo_bookingid, item_source, invoice_id, document_number, od_companyid, od_vendorid, od_customerid, default_fee, billing_item_amount_tcy, billing_item_amount_lcy, billing_item_amount_scy, invoiced_item_amount_tcy, invoiced_item_amount_lcy, invoiced_item_amount_scy, paid_item_amount_tcy, paid_item_amount_lcy, paid_item_amount_scy, currency_code_transaction, currency_code_local, currency_code_system, gd_status, gd_statusflowtype, au_useridins, insertdate, au_useridupd, modifydate, "version", dbuserins, dbuserupd, bo_booking_itemid, od_feeid)
VALUES(6291, 'INCOME', 'PLATFORM', 3583, 'TRANSACTION_FEE', NULL, NULL, 553199, NULL, 553123, 0, 6, 6, 6, NULL, NULL, NULL, NULL, NULL, NULL, 'EUR', 'EUR', 'EUR', 'OPEN', 'BILLING_ITEM', 50153, '2020-08-20 12:53:32.922', NULL, NULL, NULL, NULL, NULL, 7885, 11);
INSERT INTO bi_billing_item
(bi_billing_itemid, item_type, business_type, bo_bookingid, item_source, invoice_id, document_number, od_companyid, od_vendorid, od_customerid, default_fee, billing_item_amount_tcy, billing_item_amount_lcy, billing_item_amount_scy, invoiced_item_amount_tcy, invoiced_item_amount_lcy, invoiced_item_amount_scy, paid_item_amount_tcy, paid_item_amount_lcy, paid_item_amount_scy, currency_code_transaction, currency_code_local, currency_code_system, gd_status, gd_statusflowtype, au_useridins, insertdate, au_useridupd, modifydate, "version", dbuserins, dbuserupd, bo_booking_itemid, od_feeid)
VALUES(6302, 'INCOME', 'PURCHASE_SALE', 3584, 'PRODUCT_RATE', NULL, NULL, 553123, NULL, 553200, NULL, 28, 28, 28, NULL, NULL, NULL, NULL, NULL, NULL, 'EUR', 'EUR', 'EUR', 'OPEN', 'BILLING_ITEM', 50153, '2020-08-20 14:05:14.437', NULL, NULL, NULL, NULL, NULL, 7886, NULL);
INSERT INTO bi_billing_item
(bi_billing_itemid, item_type, business_type, bo_bookingid, item_source, invoice_id, document_number, od_companyid, od_vendorid, od_customerid, default_fee, billing_item_amount_tcy, billing_item_amount_lcy, billing_item_amount_scy, invoiced_item_amount_tcy, invoiced_item_amount_lcy, invoiced_item_amount_scy, paid_item_amount_tcy, paid_item_amount_lcy, paid_item_amount_scy, currency_code_transaction, currency_code_local, currency_code_system, gd_status, gd_statusflowtype, au_useridins, insertdate, au_useridupd, modifydate, "version", dbuserins, dbuserupd, bo_booking_itemid, od_feeid)
VALUES(6301, 'COST', 'PLATFORM', 3584, 'TRANSACTION_FEE', NULL, NULL, 553123, 553199, NULL, 0, 6, 6, 6, NULL, NULL, NULL, NULL, NULL, NULL, 'EUR', 'EUR', 'EUR', 'OPEN', 'BILLING_ITEM', 50153, '2020-08-20 14:05:11.202', NULL, NULL, NULL, NULL, NULL, 7888, 11);
INSERT INTO bi_billing_item
(bi_billing_itemid, item_type, business_type, bo_bookingid, item_source, invoice_id, document_number, od_companyid, od_vendorid, od_customerid, default_fee, billing_item_amount_tcy, billing_item_amount_lcy, billing_item_amount_scy, invoiced_item_amount_tcy, invoiced_item_amount_lcy, invoiced_item_amount_scy, paid_item_amount_tcy, paid_item_amount_lcy, paid_item_amount_scy, currency_code_transaction, currency_code_local, currency_code_system, gd_status, gd_statusflowtype, au_useridins, insertdate, au_useridupd, modifydate, "version", dbuserins, dbuserupd, bo_booking_itemid, od_feeid)
VALUES(6300, 'INCOME', 'PLATFORM', 3584, 'TRANSACTION_FEE', NULL, NULL, 553199, NULL, 553123, 0, 6, 6, 6, NULL, NULL, NULL, NULL, NULL, NULL, 'EUR', 'EUR', 'EUR', 'OPEN', 'BILLING_ITEM', 50153, '2020-08-20 14:05:11.056', NULL, NULL, NULL, NULL, NULL, 7888, 11);
INSERT INTO bi_billing_item
(bi_billing_itemid, item_type, business_type, bo_bookingid, item_source, invoice_id, document_number, od_companyid, od_vendorid, od_customerid, default_fee, billing_item_amount_tcy, billing_item_amount_lcy, billing_item_amount_scy, invoiced_item_amount_tcy, invoiced_item_amount_lcy, invoiced_item_amount_scy, paid_item_amount_tcy, paid_item_amount_lcy, paid_item_amount_scy, currency_code_transaction, currency_code_local, currency_code_system, gd_status, gd_statusflowtype, au_useridins, insertdate, au_useridupd, modifydate, "version", dbuserins, dbuserupd, bo_booking_itemid, od_feeid)
VALUES(6303, 'INCOME', 'PURCHASE_SALE', 3585, 'PRODUCT_RATE', NULL, NULL, 553123, NULL, 553200, NULL, 28, 28, 28, NULL, NULL, NULL, NULL, NULL, NULL, 'EUR', 'EUR', 'EUR', 'OPEN', 'BILLING_ITEM', 50153, '2020-08-20 14:17:01.591', NULL, NULL, NULL, NULL, NULL, 7889, NULL);
INSERT INTO bi_billing_item
(bi_billing_itemid, item_type, business_type, bo_bookingid, item_source, invoice_id, document_number, od_companyid, od_vendorid, od_customerid, default_fee, billing_item_amount_tcy, billing_item_amount_lcy, billing_item_amount_scy, invoiced_item_amount_tcy, invoiced_item_amount_lcy, invoiced_item_amount_scy, paid_item_amount_tcy, paid_item_amount_lcy, paid_item_amount_scy, currency_code_transaction, currency_code_local, currency_code_system, gd_status, gd_statusflowtype, au_useridins, insertdate, au_useridupd, modifydate, "version", dbuserins, dbuserupd, bo_booking_itemid, od_feeid)
VALUES(6305, 'INCOME', 'PLATFORM', 3585, 'TRANSACTION_FEE', NULL, NULL, 553199, NULL, 553123, 0, 6, 6, 6, NULL, NULL, NULL, NULL, NULL, NULL, 'EUR', 'EUR', 'EUR', 'OPEN', 'BILLING_ITEM', 50153, '2020-08-20 14:17:04.181', NULL, NULL, NULL, NULL, NULL, 7891, 11);
INSERT INTO bi_billing_item
(bi_billing_itemid, item_type, business_type, bo_bookingid, item_source, invoice_id, document_number, od_companyid, od_vendorid, od_customerid, default_fee, billing_item_amount_tcy, billing_item_amount_lcy, billing_item_amount_scy, invoiced_item_amount_tcy, invoiced_item_amount_lcy, invoiced_item_amount_scy, paid_item_amount_tcy, paid_item_amount_lcy, paid_item_amount_scy, currency_code_transaction, currency_code_local, currency_code_system, gd_status, gd_statusflowtype, au_useridins, insertdate, au_useridupd, modifydate, "version", dbuserins, dbuserupd, bo_booking_itemid, od_feeid)
VALUES(6304, 'COST', 'PLATFORM', 3585, 'TRANSACTION_FEE', NULL, NULL, 553123, 553199, NULL, 0, 6, 6, 6, NULL, NULL, NULL, NULL, NULL, NULL, 'EUR', 'EUR', 'EUR', 'OPEN', 'BILLING_ITEM', 50153, '2020-08-20 14:17:04.057', NULL, NULL, NULL, NULL, NULL, 7891, 11);
INSERT INTO bi_billing_item
(bi_billing_itemid, item_type, business_type, bo_bookingid, item_source, invoice_id, document_number, od_companyid, od_vendorid, od_customerid, default_fee, billing_item_amount_tcy, billing_item_amount_lcy, billing_item_amount_scy, invoiced_item_amount_tcy, invoiced_item_amount_lcy, invoiced_item_amount_scy, paid_item_amount_tcy, paid_item_amount_lcy, paid_item_amount_scy, currency_code_transaction, currency_code_local, currency_code_system, gd_status, gd_statusflowtype, au_useridins, insertdate, au_useridupd, modifydate, "version", dbuserins, dbuserupd, bo_booking_itemid, od_feeid)
VALUES(6306, 'INCOME', 'PURCHASE_SALE', 3586, 'PRODUCT_RATE', NULL, NULL, 553123, NULL, 553200, NULL, 28, 28, 28, NULL, NULL, NULL, NULL, NULL, NULL, 'EUR', 'EUR', 'EUR', 'OPEN', 'BILLING_ITEM', 50153, '2020-08-25 18:28:58.386', NULL, NULL, NULL, NULL, NULL, 7892, NULL);
INSERT INTO bi_billing_item
(bi_billing_itemid, item_type, business_type, bo_bookingid, item_source, invoice_id, document_number, od_companyid, od_vendorid, od_customerid, default_fee, billing_item_amount_tcy, billing_item_amount_lcy, billing_item_amount_scy, invoiced_item_amount_tcy, invoiced_item_amount_lcy, invoiced_item_amount_scy, paid_item_amount_tcy, paid_item_amount_lcy, paid_item_amount_scy, currency_code_transaction, currency_code_local, currency_code_system, gd_status, gd_statusflowtype, au_useridins, insertdate, au_useridupd, modifydate, "version", dbuserins, dbuserupd, bo_booking_itemid, od_feeid)
VALUES(6308, 'INCOME', 'PLATFORM', 3586, 'TRANSACTION_FEE', NULL, NULL, 553199, NULL, 553123, 0, 6, 6, 6, NULL, NULL, NULL, NULL, NULL, NULL, 'EUR', 'EUR', 'EUR', 'OPEN', 'BILLING_ITEM', 50153, '2020-08-25 18:29:06.349', NULL, NULL, NULL, NULL, NULL, 7894, 11);
INSERT INTO bi_billing_item
(bi_billing_itemid, item_type, business_type, bo_bookingid, item_source, invoice_id, document_number, od_companyid, od_vendorid, od_customerid, default_fee, billing_item_amount_tcy, billing_item_amount_lcy, billing_item_amount_scy, invoiced_item_amount_tcy, invoiced_item_amount_lcy, invoiced_item_amount_scy, paid_item_amount_tcy, paid_item_amount_lcy, paid_item_amount_scy, currency_code_transaction, currency_code_local, currency_code_system, gd_status, gd_statusflowtype, au_useridins, insertdate, au_useridupd, modifydate, "version", dbuserins, dbuserupd, bo_booking_itemid, od_feeid)
VALUES(6307, 'COST', 'PLATFORM', 3586, 'TRANSACTION_FEE', NULL, NULL, 553123, 553199, NULL, 0, 6, 6, 6, NULL, NULL, NULL, NULL, NULL, NULL, 'EUR', 'EUR', 'EUR', 'OPEN', 'BILLING_ITEM', 50153, '2020-08-25 18:29:05.967', NULL, NULL, NULL, NULL, NULL, 7894, 11);
INSERT INTO bi_billing_item
(bi_billing_itemid, item_type, business_type, bo_bookingid, item_source, invoice_id, document_number, od_companyid, od_vendorid, od_customerid, default_fee, billing_item_amount_tcy, billing_item_amount_lcy, billing_item_amount_scy, invoiced_item_amount_tcy, invoiced_item_amount_lcy, invoiced_item_amount_scy, paid_item_amount_tcy, paid_item_amount_lcy, paid_item_amount_scy, currency_code_transaction, currency_code_local, currency_code_system, gd_status, gd_statusflowtype, au_useridins, insertdate, au_useridupd, modifydate, "version", dbuserins, dbuserupd, bo_booking_itemid, od_feeid)
VALUES(6310, 'INCOME', 'PURCHASE_SALE', 3587, 'PRODUCT_RATE', NULL, NULL, 553123, NULL, 553200, NULL, 28, 28, 28, NULL, NULL, NULL, NULL, NULL, NULL, 'EUR', 'EUR', 'EUR', 'OPEN', 'BILLING_ITEM', 50153, '2020-08-25 19:10:03.323', NULL, NULL, NULL, NULL, NULL, 7895, NULL);
INSERT INTO bi_billing_item
(bi_billing_itemid, item_type, business_type, bo_bookingid, item_source, invoice_id, document_number, od_companyid, od_vendorid, od_customerid, default_fee, billing_item_amount_tcy, billing_item_amount_lcy, billing_item_amount_scy, invoiced_item_amount_tcy, invoiced_item_amount_lcy, invoiced_item_amount_scy, paid_item_amount_tcy, paid_item_amount_lcy, paid_item_amount_scy, currency_code_transaction, currency_code_local, currency_code_system, gd_status, gd_statusflowtype, au_useridins, insertdate, au_useridupd, modifydate, "version", dbuserins, dbuserupd, bo_booking_itemid, od_feeid)
VALUES(6311, 'COST', 'PLATFORM', 3587, 'TRANSACTION_FEE', NULL, NULL, 553123, 553199, NULL, 0, 6, 6, 6, NULL, NULL, NULL, NULL, NULL, NULL, 'EUR', 'EUR', 'EUR', 'OPEN', 'BILLING_ITEM', 50153, '2020-08-25 19:10:03.646', NULL, NULL, NULL, NULL, NULL, 7897, 11);
INSERT INTO bi_billing_item
(bi_billing_itemid, item_type, business_type, bo_bookingid, item_source, invoice_id, document_number, od_companyid, od_vendorid, od_customerid, default_fee, billing_item_amount_tcy, billing_item_amount_lcy, billing_item_amount_scy, invoiced_item_amount_tcy, invoiced_item_amount_lcy, invoiced_item_amount_scy, paid_item_amount_tcy, paid_item_amount_lcy, paid_item_amount_scy, currency_code_transaction, currency_code_local, currency_code_system, gd_status, gd_statusflowtype, au_useridins, insertdate, au_useridupd, modifydate, "version", dbuserins, dbuserupd, bo_booking_itemid, od_feeid)
VALUES(6309, 'INCOME', 'PLATFORM', 3587, 'TRANSACTION_FEE', NULL, NULL, 553199, NULL, 553123, 0, 6, 6, 6, NULL, NULL, NULL, NULL, NULL, NULL, 'EUR', 'EUR', 'EUR', 'OPEN', 'BILLING_ITEM', 50153, '2020-08-25 19:09:55.799', NULL, NULL, NULL, NULL, NULL, 7897, 11);
INSERT INTO bi_billing_item
(bi_billing_itemid, item_type, business_type, bo_bookingid, item_source, invoice_id, document_number, od_companyid, od_vendorid, od_customerid, default_fee, billing_item_amount_tcy, billing_item_amount_lcy, billing_item_amount_scy, invoiced_item_amount_tcy, invoiced_item_amount_lcy, invoiced_item_amount_scy, paid_item_amount_tcy, paid_item_amount_lcy, paid_item_amount_scy, currency_code_transaction, currency_code_local, currency_code_system, gd_status, gd_statusflowtype, au_useridins, insertdate, au_useridupd, modifydate, "version", dbuserins, dbuserupd, bo_booking_itemid, od_feeid)
VALUES(6313, 'INCOME', 'PURCHASE_SALE', 3588, 'PRODUCT_RATE', NULL, NULL, 553123, NULL, 553200, NULL, 28, 28, 28, NULL, NULL, NULL, NULL, NULL, NULL, 'EUR', 'EUR', 'EUR', 'OPEN', 'BILLING_ITEM', 50153, '2020-08-25 19:12:41.239', NULL, NULL, NULL, NULL, NULL, 7898, NULL);
INSERT INTO bi_billing_item
(bi_billing_itemid, item_type, business_type, bo_bookingid, item_source, invoice_id, document_number, od_companyid, od_vendorid, od_customerid, default_fee, billing_item_amount_tcy, billing_item_amount_lcy, billing_item_amount_scy, invoiced_item_amount_tcy, invoiced_item_amount_lcy, invoiced_item_amount_scy, paid_item_amount_tcy, paid_item_amount_lcy, paid_item_amount_scy, currency_code_transaction, currency_code_local, currency_code_system, gd_status, gd_statusflowtype, au_useridins, insertdate, au_useridupd, modifydate, "version", dbuserins, dbuserupd, bo_booking_itemid, od_feeid)
VALUES(6314, 'INCOME', 'PLATFORM', 3588, 'TRANSACTION_FEE', NULL, NULL, 553199, NULL, 553123, 0, 6, 6, 6, NULL, NULL, NULL, NULL, NULL, NULL, 'EUR', 'EUR', 'EUR', 'OPEN', 'BILLING_ITEM', 50153, '2020-08-25 19:12:41.547', NULL, NULL, NULL, NULL, NULL, 7900, 11);
INSERT INTO bi_billing_item
(bi_billing_itemid, item_type, business_type, bo_bookingid, item_source, invoice_id, document_number, od_companyid, od_vendorid, od_customerid, default_fee, billing_item_amount_tcy, billing_item_amount_lcy, billing_item_amount_scy, invoiced_item_amount_tcy, invoiced_item_amount_lcy, invoiced_item_amount_scy, paid_item_amount_tcy, paid_item_amount_lcy, paid_item_amount_scy, currency_code_transaction, currency_code_local, currency_code_system, gd_status, gd_statusflowtype, au_useridins, insertdate, au_useridupd, modifydate, "version", dbuserins, dbuserupd, bo_booking_itemid, od_feeid)
VALUES(6312, 'COST', 'PLATFORM', 3588, 'TRANSACTION_FEE', NULL, NULL, 553123, 553199, NULL, 0, 6, 6, 6, NULL, NULL, NULL, NULL, NULL, NULL, 'EUR', 'EUR', 'EUR', 'OPEN', 'BILLING_ITEM', 50153, '2020-08-25 19:12:34.514', NULL, NULL, NULL, NULL, NULL, 7900, 11);
