INSERT INTO bi_billing_item
(item_type, business_type, bo_bookingid, item_source, invoice_id, document_number, od_companyid, od_vendorid, od_customerid, default_fee, billing_item_amount_tcy, billing_item_amount_lcy, billing_item_amount_scy, invoiced_item_amount_tcy, invoiced_item_amount_lcy, invoiced_item_amount_scy, paid_item_amount_tcy, paid_item_amount_lcy, paid_item_amount_scy, currency_code_transaction, currency_code_local, currency_code_system, gd_status, gd_statusflowtype, au_useridins, insertdate, au_useridupd, modifydate, version, dbuserins, dbuserupd, bo_booking_itemid, od_feeid)
VALUES( 'INCOME', 'PLATFORM', 3565, 'TRANSACTION_FEE', NULL, NULL, 553199, NULL, 553123, 0, 3, 3, 3, NULL, NULL, NULL, NULL, NULL, NULL, 'EUR', 'EUR', 'EUR', 'OPEN', 'BILLING_ITEM', 50153, '2020-07-24 12:10:53.894', NULL, NULL, NULL, NULL, NULL, 44, 11);
INSERT INTO bi_billing_item
(item_type, business_type, bo_bookingid, item_source, invoice_id, document_number, od_companyid, od_vendorid, od_customerid, default_fee, billing_item_amount_tcy, billing_item_amount_lcy, billing_item_amount_scy, invoiced_item_amount_tcy, invoiced_item_amount_lcy, invoiced_item_amount_scy, paid_item_amount_tcy, paid_item_amount_lcy, paid_item_amount_scy, currency_code_transaction, currency_code_local, currency_code_system, gd_status, gd_statusflowtype, au_useridins, insertdate, au_useridupd, modifydate, version, dbuserins, dbuserupd, bo_booking_itemid, od_feeid)
VALUES( 'COST', 'PLATFORM', 3565, 'TRANSACTION_FEE', NULL, NULL, 553123, 553199, NULL, 0, 3, 3, 3, NULL, NULL, NULL, NULL, NULL, NULL, 'EUR', 'EUR', 'EUR', 'OPEN', 'BILLING_ITEM', 50153, '2020-07-24 12:10:53.798', NULL, NULL, NULL, NULL, NULL, 44, 11);
INSERT INTO bi_billing_item
(item_type, business_type, bo_bookingid, item_source, invoice_id, document_number, od_companyid, od_vendorid, od_customerid, default_fee, billing_item_amount_tcy, billing_item_amount_lcy, billing_item_amount_scy, invoiced_item_amount_tcy, invoiced_item_amount_lcy, invoiced_item_amount_scy, paid_item_amount_tcy, paid_item_amount_lcy, paid_item_amount_scy, currency_code_transaction, currency_code_local, currency_code_system, gd_status, gd_statusflowtype, au_useridins, insertdate, au_useridupd, modifydate, version, dbuserins, dbuserupd, bo_booking_itemid, od_feeid)
VALUES( 'INCOME', 'PURCHASE_SALE', 3566, 'PRODUCT_RATE', NULL, NULL, 553123, NULL, 553200, NULL, 14, 14, 14, NULL, NULL, NULL, NULL, NULL, NULL, 'EUR', 'EUR', 'EUR', 'OPEN', 'BILLING_ITEM', 50153, '2020-07-24 13:00:11.299', NULL, NULL, NULL, NULL, NULL, 43, NULL);
INSERT INTO bi_billing_item
(item_type, business_type, bo_bookingid, item_source, invoice_id, document_number, od_companyid, od_vendorid, od_customerid, default_fee, billing_item_amount_tcy, billing_item_amount_lcy, billing_item_amount_scy, invoiced_item_amount_tcy, invoiced_item_amount_lcy, invoiced_item_amount_scy, paid_item_amount_tcy, paid_item_amount_lcy, paid_item_amount_scy, currency_code_transaction, currency_code_local, currency_code_system, gd_status, gd_statusflowtype, au_useridins, insertdate, au_useridupd, modifydate, version, dbuserins, dbuserupd, bo_booking_itemid, od_feeid)
VALUES( 'INCOME', 'PLATFORM', 3566, 'TRANSACTION_FEE', NULL, NULL, 553199, NULL, 553123, 0, 3, 3, 3, NULL, NULL, NULL, NULL, NULL, NULL, 'EUR', 'EUR', 'EUR', 'OPEN', 'BILLING_ITEM', 50153, '2020-07-24 13:00:10.498', NULL, NULL, NULL, NULL, NULL, 41, 11);
INSERT INTO bi_billing_item
(item_type, business_type, bo_bookingid, item_source, invoice_id, document_number, od_companyid, od_vendorid, od_customerid, default_fee, billing_item_amount_tcy, billing_item_amount_lcy, billing_item_amount_scy, invoiced_item_amount_tcy, invoiced_item_amount_lcy, invoiced_item_amount_scy, paid_item_amount_tcy, paid_item_amount_lcy, paid_item_amount_scy, currency_code_transaction, currency_code_local, currency_code_system, gd_status, gd_statusflowtype, au_useridins, insertdate, au_useridupd, modifydate, version, dbuserins, dbuserupd, bo_booking_itemid, od_feeid)
VALUES( 'COST', 'PLATFORM', 3566, 'TRANSACTION_FEE', NULL, NULL, 553123, 553199, NULL, 0, 3, 3, 3, NULL, NULL, NULL, NULL, NULL, NULL, 'EUR', 'EUR', 'EUR', 'OPEN', 'BILLING_ITEM', 50153, '2020-07-24 13:00:10.433', NULL, NULL, NULL, NULL, NULL, 41, 11);
INSERT INTO bi_billing_item
(item_type, business_type, bo_bookingid, item_source, invoice_id, document_number, od_companyid, od_vendorid, od_customerid, default_fee, billing_item_amount_tcy, billing_item_amount_lcy, billing_item_amount_scy, invoiced_item_amount_tcy, invoiced_item_amount_lcy, invoiced_item_amount_scy, paid_item_amount_tcy, paid_item_amount_lcy, paid_item_amount_scy, currency_code_transaction, currency_code_local, currency_code_system, gd_status, gd_statusflowtype, au_useridins, insertdate, au_useridupd, modifydate, version, dbuserins, dbuserupd, bo_booking_itemid, od_feeid)
VALUES( 'INCOME', 'PURCHASE_SALE', 3573, 'PRODUCT_RATE', NULL, NULL, 553123, NULL, 553200, NULL, 58, 58, 58, NULL, NULL, NULL, NULL, NULL, NULL, 'EUR', 'EUR', 'EUR', 'VOID', 'BILLING_ITEM', 50153, '2020-08-14 09:14:17.645', NULL, NULL, NULL, NULL, NULL, 37, NULL);
INSERT INTO bi_billing_item
(item_type, business_type, bo_bookingid, item_source, invoice_id, document_number, od_companyid, od_vendorid, od_customerid, default_fee, billing_item_amount_tcy, billing_item_amount_lcy, billing_item_amount_scy, invoiced_item_amount_tcy, invoiced_item_amount_lcy, invoiced_item_amount_scy, paid_item_amount_tcy, paid_item_amount_lcy, paid_item_amount_scy, currency_code_transaction, currency_code_local, currency_code_system, gd_status, gd_statusflowtype, au_useridins, insertdate, au_useridupd, modifydate, version, dbuserins, dbuserupd, bo_booking_itemid, od_feeid)
VALUES( 'COST', 'GATEWAY_CARD', 3573, 'GATEWAY_FEE', NULL, NULL, 553199, 558075, NULL, 0, 4, 4, 4, NULL, NULL, NULL, NULL, NULL, NULL, 'EUR', 'EUR', 'EUR', 'OPEN', 'BILLING_ITEM', NULL, '2020-08-12 12:39:45.251', NULL, NULL, NULL, NULL, NULL, 36, 13);
INSERT INTO bi_billing_item
(item_type, business_type, bo_bookingid, item_source, invoice_id, document_number, od_companyid, od_vendorid, od_customerid, default_fee, billing_item_amount_tcy, billing_item_amount_lcy, billing_item_amount_scy, invoiced_item_amount_tcy, invoiced_item_amount_lcy, invoiced_item_amount_scy, paid_item_amount_tcy, paid_item_amount_lcy, paid_item_amount_scy, currency_code_transaction, currency_code_local, currency_code_system, gd_status, gd_statusflowtype, au_useridins, insertdate, au_useridupd, modifydate, version, dbuserins, dbuserupd, bo_booking_itemid, od_feeid)
VALUES( 'COST', 'GATEWAY_CARD', 3573, 'GATEWAY_FEE', NULL, NULL, 553199, 558075, NULL, 0, 0.87, 0.87, 0.87, NULL, NULL, NULL, NULL, NULL, NULL, 'EUR', 'EUR', 'EUR', 'OPEN', 'BILLING_ITEM', NULL, '2020-08-12 12:39:44.147', NULL, NULL, NULL, NULL, NULL, 36, 14);
INSERT INTO bi_billing_item
(item_type, business_type, bo_bookingid, item_source, invoice_id, document_number, od_companyid, od_vendorid, od_customerid, default_fee, billing_item_amount_tcy, billing_item_amount_lcy, billing_item_amount_scy, invoiced_item_amount_tcy, invoiced_item_amount_lcy, invoiced_item_amount_scy, paid_item_amount_tcy, paid_item_amount_lcy, paid_item_amount_scy, currency_code_transaction, currency_code_local, currency_code_system, gd_status, gd_statusflowtype, au_useridins, insertdate, au_useridupd, modifydate, version, dbuserins, dbuserupd, bo_booking_itemid, od_feeid)
VALUES( 'INCOME', 'PLATFORM', 3573, 'PAYMENT_FEE', NULL, NULL, 553199, NULL, 553123, 0, 0.87, 0.87, 0.87, NULL, NULL, NULL, NULL, NULL, NULL, 'EUR', 'EUR', 'EUR', 'OPEN', 'BILLING_ITEM', NULL, '2020-08-12 12:39:46.663', NULL, NULL, NULL, NULL, NULL, 35, 15);
INSERT INTO bi_billing_item
(item_type, business_type, bo_bookingid, item_source, invoice_id, document_number, od_companyid, od_vendorid, od_customerid, default_fee, billing_item_amount_tcy, billing_item_amount_lcy, billing_item_amount_scy, invoiced_item_amount_tcy, invoiced_item_amount_lcy, invoiced_item_amount_scy, paid_item_amount_tcy, paid_item_amount_lcy, paid_item_amount_scy, currency_code_transaction, currency_code_local, currency_code_system, gd_status, gd_statusflowtype, au_useridins, insertdate, au_useridupd, modifydate, version, dbuserins, dbuserupd, bo_booking_itemid, od_feeid)
VALUES( 'COST', 'PLATFORM', 3573, 'PAYMENT_FEE', NULL, NULL, 553123, 553199, NULL, 0, 0.87, 0.87, 0.87, NULL, NULL, NULL, NULL, NULL, NULL, 'EUR', 'EUR', 'EUR', 'OPEN', 'BILLING_ITEM', NULL, '2020-08-12 12:39:45.756', NULL, NULL, NULL, NULL, NULL, 35, 15);
INSERT INTO bi_billing_item
(item_type, business_type, bo_bookingid, item_source, invoice_id, document_number, od_companyid, od_vendorid, od_customerid, default_fee, billing_item_amount_tcy, billing_item_amount_lcy, billing_item_amount_scy, invoiced_item_amount_tcy, invoiced_item_amount_lcy, invoiced_item_amount_scy, paid_item_amount_tcy, paid_item_amount_lcy, paid_item_amount_scy, currency_code_transaction, currency_code_local, currency_code_system, gd_status, gd_statusflowtype, au_useridins, insertdate, au_useridupd, modifydate, version, dbuserins, dbuserupd, bo_booking_itemid, od_feeid)
VALUES( 'COST', 'PLATFORM', 3573, 'TRANSACTION_FEE', NULL, NULL, 553123, 553199, NULL, 0, 9, 9, 9, NULL, NULL, NULL, NULL, NULL, NULL, 'EUR', 'EUR', 'EUR', 'OPEN', 'BILLING_ITEM', NULL, '2020-08-12 12:39:45.155', NULL, NULL, NULL, NULL, NULL, 34, 11);
INSERT INTO bi_billing_item
(item_type, business_type, bo_bookingid, item_source, invoice_id, document_number, od_companyid, od_vendorid, od_customerid, default_fee, billing_item_amount_tcy, billing_item_amount_lcy, billing_item_amount_scy, invoiced_item_amount_tcy, invoiced_item_amount_lcy, invoiced_item_amount_scy, paid_item_amount_tcy, paid_item_amount_lcy, paid_item_amount_scy, currency_code_transaction, currency_code_local, currency_code_system, gd_status, gd_statusflowtype, au_useridins, insertdate, au_useridupd, modifydate, version, dbuserins, dbuserupd, bo_booking_itemid, od_feeid)
VALUES( 'INCOME', 'PLATFORM', 3573, 'TRANSACTION_FEE', NULL, NULL, 553199, NULL, 553123, 0, 9, 9, 9, NULL, NULL, NULL, NULL, NULL, NULL, 'EUR', 'EUR', 'EUR', 'OPEN', 'BILLING_ITEM', NULL, '2020-08-12 12:39:45.145', NULL, NULL, NULL, NULL, NULL, 34, 11);
INSERT INTO bi_billing_item
(item_type, business_type, bo_bookingid, item_source, invoice_id, document_number, od_companyid, od_vendorid, od_customerid, default_fee, billing_item_amount_tcy, billing_item_amount_lcy, billing_item_amount_scy, invoiced_item_amount_tcy, invoiced_item_amount_lcy, invoiced_item_amount_scy, paid_item_amount_tcy, paid_item_amount_lcy, paid_item_amount_scy, currency_code_transaction, currency_code_local, currency_code_system, gd_status, gd_statusflowtype, au_useridins, insertdate, au_useridupd, modifydate, version, dbuserins, dbuserupd, bo_booking_itemid, od_feeid)
VALUES( 'INCOME', 'PURCHASE_SALE', 3578, 'PRODUCT_RATE', NULL, NULL, 553123, NULL, 553200, NULL, 28, 28, 28, NULL, NULL, NULL, NULL, NULL, NULL, 'EUR', 'EUR', 'EUR', 'OPEN', 'BILLING_ITEM', 50153, '2020-08-20 13:01:02.269', NULL, NULL, NULL, NULL, NULL, 33, NULL);
INSERT INTO bi_billing_item
(item_type, business_type, bo_bookingid, item_source, invoice_id, document_number, od_companyid, od_vendorid, od_customerid, default_fee, billing_item_amount_tcy, billing_item_amount_lcy, billing_item_amount_scy, invoiced_item_amount_tcy, invoiced_item_amount_lcy, invoiced_item_amount_scy, paid_item_amount_tcy, paid_item_amount_lcy, paid_item_amount_scy, currency_code_transaction, currency_code_local, currency_code_system, gd_status, gd_statusflowtype, au_useridins, insertdate, au_useridupd, modifydate, version, dbuserins, dbuserupd, bo_booking_itemid, od_feeid)
VALUES( 'INCOME', 'PLATFORM', 3578, 'TRANSACTION_FEE', NULL, NULL, 553199, NULL, 553123, 0, 6, 6, 6, NULL, NULL, NULL, NULL, NULL, NULL, 'EUR', 'EUR', 'EUR', 'OPEN', 'BILLING_ITEM', 50153, '2020-08-20 13:01:02.361', NULL, NULL, NULL, NULL, NULL, 31, 11);
INSERT INTO bi_billing_item
(item_type, business_type, bo_bookingid, item_source, invoice_id, document_number, od_companyid, od_vendorid, od_customerid, default_fee, billing_item_amount_tcy, billing_item_amount_lcy, billing_item_amount_scy, invoiced_item_amount_tcy, invoiced_item_amount_lcy, invoiced_item_amount_scy, paid_item_amount_tcy, paid_item_amount_lcy, paid_item_amount_scy, currency_code_transaction, currency_code_local, currency_code_system, gd_status, gd_statusflowtype, au_useridins, insertdate, au_useridupd, modifydate, version, dbuserins, dbuserupd, bo_booking_itemid, od_feeid)
VALUES( 'COST', 'PLATFORM', 3578, 'TRANSACTION_FEE', NULL, NULL, 553123, 553199, NULL, 0, 6, 6, 6, NULL, NULL, NULL, NULL, NULL, NULL, 'EUR', 'EUR', 'EUR', 'OPEN', 'BILLING_ITEM', 50153, '2020-08-20 13:01:01.464', NULL, NULL, NULL, NULL, NULL, 31, 11);
INSERT INTO bi_billing_item
(item_type, business_type, bo_bookingid, item_source, invoice_id, document_number, od_companyid, od_vendorid, od_customerid, default_fee, billing_item_amount_tcy, billing_item_amount_lcy, billing_item_amount_scy, invoiced_item_amount_tcy, invoiced_item_amount_lcy, invoiced_item_amount_scy, paid_item_amount_tcy, paid_item_amount_lcy, paid_item_amount_scy, currency_code_transaction, currency_code_local, currency_code_system, gd_status, gd_statusflowtype, au_useridins, insertdate, au_useridupd, modifydate, version, dbuserins, dbuserupd, bo_booking_itemid, od_feeid)
VALUES( 'INCOME', 'PURCHASE_SALE', 3579, 'PRODUCT_RATE', NULL, NULL, 553123, NULL, 553200, NULL, 28, 28, 28, NULL, NULL, NULL, NULL, NULL, NULL, 'EUR', 'EUR', 'EUR', 'OPEN', 'BILLING_ITEM', 50153, '2020-08-20 13:00:23.681', NULL, NULL, NULL, NULL, NULL, 30, NULL);
INSERT INTO bi_billing_item
(item_type, business_type, bo_bookingid, item_source, invoice_id, document_number, od_companyid, od_vendorid, od_customerid, default_fee, billing_item_amount_tcy, billing_item_amount_lcy, billing_item_amount_scy, invoiced_item_amount_tcy, invoiced_item_amount_lcy, invoiced_item_amount_scy, paid_item_amount_tcy, paid_item_amount_lcy, paid_item_amount_scy, currency_code_transaction, currency_code_local, currency_code_system, gd_status, gd_statusflowtype, au_useridins, insertdate, au_useridupd, modifydate, version, dbuserins, dbuserupd, bo_booking_itemid, od_feeid)
VALUES( 'INCOME', 'PLATFORM', 3579, 'TRANSACTION_FEE', NULL, NULL, 553199, NULL, 553123, 0, 6, 6, 6, NULL, NULL, NULL, NULL, NULL, NULL, 'EUR', 'EUR', 'EUR', 'OPEN', 'BILLING_ITEM', 50153, '2020-08-20 13:00:23.761', NULL, NULL, NULL, NULL, NULL, 28, 11);
INSERT INTO bi_billing_item
(item_type, business_type, bo_bookingid, item_source, invoice_id, document_number, od_companyid, od_vendorid, od_customerid, default_fee, billing_item_amount_tcy, billing_item_amount_lcy, billing_item_amount_scy, invoiced_item_amount_tcy, invoiced_item_amount_lcy, invoiced_item_amount_scy, paid_item_amount_tcy, paid_item_amount_lcy, paid_item_amount_scy, currency_code_transaction, currency_code_local, currency_code_system, gd_status, gd_statusflowtype, au_useridins, insertdate, au_useridupd, modifydate, version, dbuserins, dbuserupd, bo_booking_itemid, od_feeid)
VALUES( 'COST', 'PLATFORM', 3579, 'TRANSACTION_FEE', NULL, NULL, 553123, 553199, NULL, 0, 6, 6, 6, NULL, NULL, NULL, NULL, NULL, NULL, 'EUR', 'EUR', 'EUR', 'OPEN', 'BILLING_ITEM', 50153, '2020-08-20 13:00:22.668', NULL, NULL, NULL, NULL, NULL, 28, 11);
INSERT INTO bi_billing_item
(item_type, business_type, bo_bookingid, item_source, invoice_id, document_number, od_companyid, od_vendorid, od_customerid, default_fee, billing_item_amount_tcy, billing_item_amount_lcy, billing_item_amount_scy, invoiced_item_amount_tcy, invoiced_item_amount_lcy, invoiced_item_amount_scy, paid_item_amount_tcy, paid_item_amount_lcy, paid_item_amount_scy, currency_code_transaction, currency_code_local, currency_code_system, gd_status, gd_statusflowtype, au_useridins, insertdate, au_useridupd, modifydate, version, dbuserins, dbuserupd, bo_booking_itemid, od_feeid)
VALUES( 'INCOME', 'PURCHASE_SALE', 3580, 'PRODUCT_RATE', NULL, NULL, 553123, NULL, 553200, NULL, 28, 28, 28, NULL, NULL, NULL, NULL, NULL, NULL, 'EUR', 'EUR', 'EUR', 'OPEN', 'BILLING_ITEM', 50153, '2020-08-20 12:44:34.094', NULL, NULL, NULL, NULL, NULL, 27, NULL);
INSERT INTO bi_billing_item
(item_type, business_type, bo_bookingid, item_source, invoice_id, document_number, od_companyid, od_vendorid, od_customerid, default_fee, billing_item_amount_tcy, billing_item_amount_lcy, billing_item_amount_scy, invoiced_item_amount_tcy, invoiced_item_amount_lcy, invoiced_item_amount_scy, paid_item_amount_tcy, paid_item_amount_lcy, paid_item_amount_scy, currency_code_transaction, currency_code_local, currency_code_system, gd_status, gd_statusflowtype, au_useridins, insertdate, au_useridupd, modifydate, version, dbuserins, dbuserupd, bo_booking_itemid, od_feeid)
VALUES( 'COST', 'PLATFORM', 3580, 'TRANSACTION_FEE', NULL, NULL, 553123, 553199, NULL, 0, 6, 6, 6, NULL, NULL, NULL, NULL, NULL, NULL, 'EUR', 'EUR', 'EUR', 'OPEN', 'BILLING_ITEM', 50153, '2020-08-20 12:44:34.226', NULL, NULL, NULL, NULL, NULL, 25, 11);
INSERT INTO bi_billing_item
(item_type, business_type, bo_bookingid, item_source, invoice_id, document_number, od_companyid, od_vendorid, od_customerid, default_fee, billing_item_amount_tcy, billing_item_amount_lcy, billing_item_amount_scy, invoiced_item_amount_tcy, invoiced_item_amount_lcy, invoiced_item_amount_scy, paid_item_amount_tcy, paid_item_amount_lcy, paid_item_amount_scy, currency_code_transaction, currency_code_local, currency_code_system, gd_status, gd_statusflowtype, au_useridins, insertdate, au_useridupd, modifydate, version, dbuserins, dbuserupd, bo_booking_itemid, od_feeid)
VALUES( 'INCOME', 'PLATFORM', 3580, 'TRANSACTION_FEE', NULL, NULL, 553199, NULL, 553123, 0, 6, 6, 6, NULL, NULL, NULL, NULL, NULL, NULL, 'EUR', 'EUR', 'EUR', 'OPEN', 'BILLING_ITEM', 50153, '2020-08-20 12:44:31.296', NULL, NULL, NULL, NULL, NULL, 25, 11);
INSERT INTO bi_billing_item
(item_type, business_type, bo_bookingid, item_source, invoice_id, document_number, od_companyid, od_vendorid, od_customerid, default_fee, billing_item_amount_tcy, billing_item_amount_lcy, billing_item_amount_scy, invoiced_item_amount_tcy, invoiced_item_amount_lcy, invoiced_item_amount_scy, paid_item_amount_tcy, paid_item_amount_lcy, paid_item_amount_scy, currency_code_transaction, currency_code_local, currency_code_system, gd_status, gd_statusflowtype, au_useridins, insertdate, au_useridupd, modifydate, version, dbuserins, dbuserupd, bo_booking_itemid, od_feeid)
VALUES( 'INCOME', 'PURCHASE_SALE', 3581, 'PRODUCT_RATE', NULL, NULL, 553123, NULL, 553200, NULL, 28, 28, 28, NULL, NULL, NULL, NULL, NULL, NULL, 'EUR', 'EUR', 'EUR', 'OPEN', 'BILLING_ITEM', 50153, '2020-08-20 12:45:42.892', NULL, NULL, NULL, NULL, NULL, 24, NULL);
INSERT INTO bi_billing_item
(item_type, business_type, bo_bookingid, item_source, invoice_id, document_number, od_companyid, od_vendorid, od_customerid, default_fee, billing_item_amount_tcy, billing_item_amount_lcy, billing_item_amount_scy, invoiced_item_amount_tcy, invoiced_item_amount_lcy, invoiced_item_amount_scy, paid_item_amount_tcy, paid_item_amount_lcy, paid_item_amount_scy, currency_code_transaction, currency_code_local, currency_code_system, gd_status, gd_statusflowtype, au_useridins, insertdate, au_useridupd, modifydate, version, dbuserins, dbuserupd, bo_booking_itemid, od_feeid)
VALUES( 'COST', 'PLATFORM', 3581, 'TRANSACTION_FEE', NULL, NULL, 553123, 553199, NULL, 0, 6, 6, 6, NULL, NULL, NULL, NULL, NULL, NULL, 'EUR', 'EUR', 'EUR', 'OPEN', 'BILLING_ITEM', 50153, '2020-08-20 12:45:39.897', NULL, NULL, NULL, NULL, NULL, 22, 11);
INSERT INTO bi_billing_item
(item_type, business_type, bo_bookingid, item_source, invoice_id, document_number, od_companyid, od_vendorid, od_customerid, default_fee, billing_item_amount_tcy, billing_item_amount_lcy, billing_item_amount_scy, invoiced_item_amount_tcy, invoiced_item_amount_lcy, invoiced_item_amount_scy, paid_item_amount_tcy, paid_item_amount_lcy, paid_item_amount_scy, currency_code_transaction, currency_code_local, currency_code_system, gd_status, gd_statusflowtype, au_useridins, insertdate, au_useridupd, modifydate, version, dbuserins, dbuserupd, bo_booking_itemid, od_feeid)
VALUES( 'INCOME', 'PLATFORM', 3581, 'TRANSACTION_FEE', NULL, NULL, 553199, NULL, 553123, 0, 6, 6, 6, NULL, NULL, NULL, NULL, NULL, NULL, 'EUR', 'EUR', 'EUR', 'OPEN', 'BILLING_ITEM', 50153, '2020-08-20 12:45:39.768', NULL, NULL, NULL, NULL, NULL, 22, 11);
INSERT INTO bi_billing_item
(item_type, business_type, bo_bookingid, item_source, invoice_id, document_number, od_companyid, od_vendorid, od_customerid, default_fee, billing_item_amount_tcy, billing_item_amount_lcy, billing_item_amount_scy, invoiced_item_amount_tcy, invoiced_item_amount_lcy, invoiced_item_amount_scy, paid_item_amount_tcy, paid_item_amount_lcy, paid_item_amount_scy, currency_code_transaction, currency_code_local, currency_code_system, gd_status, gd_statusflowtype, au_useridins, insertdate, au_useridupd, modifydate, version, dbuserins, dbuserupd, bo_booking_itemid, od_feeid)
VALUES( 'INCOME', 'PURCHASE_SALE', 3582, 'PRODUCT_RATE', NULL, NULL, 553123, NULL, 553200, NULL, 28, 28, 28, NULL, NULL, NULL, NULL, NULL, NULL, 'EUR', 'EUR', 'EUR', 'OPEN', 'BILLING_ITEM', 50153, '2020-08-20 12:48:01.879', NULL, NULL, NULL, NULL, NULL, 21, NULL);
INSERT INTO bi_billing_item
(item_type, business_type, bo_bookingid, item_source, invoice_id, document_number, od_companyid, od_vendorid, od_customerid, default_fee, billing_item_amount_tcy, billing_item_amount_lcy, billing_item_amount_scy, invoiced_item_amount_tcy, invoiced_item_amount_lcy, invoiced_item_amount_scy, paid_item_amount_tcy, paid_item_amount_lcy, paid_item_amount_scy, currency_code_transaction, currency_code_local, currency_code_system, gd_status, gd_statusflowtype, au_useridins, insertdate, au_useridupd, modifydate, version, dbuserins, dbuserupd, bo_booking_itemid, od_feeid)
VALUES( 'INCOME', 'PLATFORM', 3582, 'TRANSACTION_FEE', NULL, NULL, 553199, NULL, 553123, 0, 6, 6, 6, NULL, NULL, NULL, NULL, NULL, NULL, 'EUR', 'EUR', 'EUR', 'OPEN', 'BILLING_ITEM', 50153, '2020-08-20 12:48:02.028', NULL, NULL, NULL, NULL, NULL, 19, 11);
INSERT INTO bi_billing_item
(item_type, business_type, bo_bookingid, item_source, invoice_id, document_number, od_companyid, od_vendorid, od_customerid, default_fee, billing_item_amount_tcy, billing_item_amount_lcy, billing_item_amount_scy, invoiced_item_amount_tcy, invoiced_item_amount_lcy, invoiced_item_amount_scy, paid_item_amount_tcy, paid_item_amount_lcy, paid_item_amount_scy, currency_code_transaction, currency_code_local, currency_code_system, gd_status, gd_statusflowtype, au_useridins, insertdate, au_useridupd, modifydate, version, dbuserins, dbuserupd, bo_booking_itemid, od_feeid)
VALUES( 'COST', 'PLATFORM', 3582, 'TRANSACTION_FEE', NULL, NULL, 553123, 553199, NULL, 0, 6, 6, 6, NULL, NULL, NULL, NULL, NULL, NULL, 'EUR', 'EUR', 'EUR', 'OPEN', 'BILLING_ITEM', 50153, '2020-08-20 12:47:58.951', NULL, NULL, NULL, NULL, NULL, 19, 11);
INSERT INTO bi_billing_item
(item_type, business_type, bo_bookingid, item_source, invoice_id, document_number, od_companyid, od_vendorid, od_customerid, default_fee, billing_item_amount_tcy, billing_item_amount_lcy, billing_item_amount_scy, invoiced_item_amount_tcy, invoiced_item_amount_lcy, invoiced_item_amount_scy, paid_item_amount_tcy, paid_item_amount_lcy, paid_item_amount_scy, currency_code_transaction, currency_code_local, currency_code_system, gd_status, gd_statusflowtype, au_useridins, insertdate, au_useridupd, modifydate, version, dbuserins, dbuserupd, bo_booking_itemid, od_feeid)
VALUES( 'INCOME', 'PURCHASE_SALE', 3583, 'PRODUCT_RATE', NULL, NULL, 553123, NULL, 553200, NULL, 28, 28, 28, NULL, NULL, NULL, NULL, NULL, NULL, 'EUR', 'EUR', 'EUR', 'OPEN', 'BILLING_ITEM', 50153, '2020-08-20 12:53:35.818', NULL, NULL, NULL, NULL, NULL, 18, NULL);
INSERT INTO bi_billing_item
(item_type, business_type, bo_bookingid, item_source, invoice_id, document_number, od_companyid, od_vendorid, od_customerid, default_fee, billing_item_amount_tcy, billing_item_amount_lcy, billing_item_amount_scy, invoiced_item_amount_tcy, invoiced_item_amount_lcy, invoiced_item_amount_scy, paid_item_amount_tcy, paid_item_amount_lcy, paid_item_amount_scy, currency_code_transaction, currency_code_local, currency_code_system, gd_status, gd_statusflowtype, au_useridins, insertdate, au_useridupd, modifydate, version, dbuserins, dbuserupd, bo_booking_itemid, od_feeid)
VALUES( 'COST', 'PLATFORM', 3583, 'TRANSACTION_FEE', NULL, NULL, 553123, 553199, NULL, 0, 6, 6, 6, NULL, NULL, NULL, NULL, NULL, NULL, 'EUR', 'EUR', 'EUR', 'OPEN', 'BILLING_ITEM', 50153, '2020-08-20 12:53:33.048', NULL, NULL, NULL, NULL, NULL, 16, 11);
INSERT INTO bi_billing_item
(item_type, business_type, bo_bookingid, item_source, invoice_id, document_number, od_companyid, od_vendorid, od_customerid, default_fee, billing_item_amount_tcy, billing_item_amount_lcy, billing_item_amount_scy, invoiced_item_amount_tcy, invoiced_item_amount_lcy, invoiced_item_amount_scy, paid_item_amount_tcy, paid_item_amount_lcy, paid_item_amount_scy, currency_code_transaction, currency_code_local, currency_code_system, gd_status, gd_statusflowtype, au_useridins, insertdate, au_useridupd, modifydate, version, dbuserins, dbuserupd, bo_booking_itemid, od_feeid)
VALUES( 'INCOME', 'PLATFORM', 3583, 'TRANSACTION_FEE', NULL, NULL, 553199, NULL, 553123, 0, 6, 6, 6, NULL, NULL, NULL, NULL, NULL, NULL, 'EUR', 'EUR', 'EUR', 'OPEN', 'BILLING_ITEM', 50153, '2020-08-20 12:53:32.922', NULL, NULL, NULL, NULL, NULL, 16, 11);
INSERT INTO bi_billing_item
(item_type, business_type, bo_bookingid, item_source, invoice_id, document_number, od_companyid, od_vendorid, od_customerid, default_fee, billing_item_amount_tcy, billing_item_amount_lcy, billing_item_amount_scy, invoiced_item_amount_tcy, invoiced_item_amount_lcy, invoiced_item_amount_scy, paid_item_amount_tcy, paid_item_amount_lcy, paid_item_amount_scy, currency_code_transaction, currency_code_local, currency_code_system, gd_status, gd_statusflowtype, au_useridins, insertdate, au_useridupd, modifydate, version, dbuserins, dbuserupd, bo_booking_itemid, od_feeid)
VALUES( 'INCOME', 'PURCHASE_SALE', 3584, 'PRODUCT_RATE', NULL, NULL, 553123, NULL, 553200, NULL, 28, 28, 28, NULL, NULL, NULL, NULL, NULL, NULL, 'EUR', 'EUR', 'EUR', 'OPEN', 'BILLING_ITEM', 50153, '2020-08-20 14:05:14.437', NULL, NULL, NULL, NULL, NULL, 15, NULL);
INSERT INTO bi_billing_item
(item_type, business_type, bo_bookingid, item_source, invoice_id, document_number, od_companyid, od_vendorid, od_customerid, default_fee, billing_item_amount_tcy, billing_item_amount_lcy, billing_item_amount_scy, invoiced_item_amount_tcy, invoiced_item_amount_lcy, invoiced_item_amount_scy, paid_item_amount_tcy, paid_item_amount_lcy, paid_item_amount_scy, currency_code_transaction, currency_code_local, currency_code_system, gd_status, gd_statusflowtype, au_useridins, insertdate, au_useridupd, modifydate, version, dbuserins, dbuserupd, bo_booking_itemid, od_feeid)
VALUES( 'COST', 'PLATFORM', 3584, 'TRANSACTION_FEE', NULL, NULL, 553123, 553199, NULL, 0, 6, 6, 6, NULL, NULL, NULL, NULL, NULL, NULL, 'EUR', 'EUR', 'EUR', 'OPEN', 'BILLING_ITEM', 50153, '2020-08-20 14:05:11.202', NULL, NULL, NULL, NULL, NULL, 13, 11);
INSERT INTO bi_billing_item
(item_type, business_type, bo_bookingid, item_source, invoice_id, document_number, od_companyid, od_vendorid, od_customerid, default_fee, billing_item_amount_tcy, billing_item_amount_lcy, billing_item_amount_scy, invoiced_item_amount_tcy, invoiced_item_amount_lcy, invoiced_item_amount_scy, paid_item_amount_tcy, paid_item_amount_lcy, paid_item_amount_scy, currency_code_transaction, currency_code_local, currency_code_system, gd_status, gd_statusflowtype, au_useridins, insertdate, au_useridupd, modifydate, version, dbuserins, dbuserupd, bo_booking_itemid, od_feeid)
VALUES( 'INCOME', 'PLATFORM', 3584, 'TRANSACTION_FEE', NULL, NULL, 553199, NULL, 553123, 0, 6, 6, 6, NULL, NULL, NULL, NULL, NULL, NULL, 'EUR', 'EUR', 'EUR', 'OPEN', 'BILLING_ITEM', 50153, '2020-08-20 14:05:11.056', NULL, NULL, NULL, NULL, NULL, 13, 11);
INSERT INTO bi_billing_item
(item_type, business_type, bo_bookingid, item_source, invoice_id, document_number, od_companyid, od_vendorid, od_customerid, default_fee, billing_item_amount_tcy, billing_item_amount_lcy, billing_item_amount_scy, invoiced_item_amount_tcy, invoiced_item_amount_lcy, invoiced_item_amount_scy, paid_item_amount_tcy, paid_item_amount_lcy, paid_item_amount_scy, currency_code_transaction, currency_code_local, currency_code_system, gd_status, gd_statusflowtype, au_useridins, insertdate, au_useridupd, modifydate, version, dbuserins, dbuserupd, bo_booking_itemid, od_feeid)
VALUES( 'INCOME', 'PURCHASE_SALE', 3585, 'PRODUCT_RATE', NULL, NULL, 553123, NULL, 553200, NULL, 28, 28, 28, NULL, NULL, NULL, NULL, NULL, NULL, 'EUR', 'EUR', 'EUR', 'OPEN', 'BILLING_ITEM', 50153, '2020-08-20 14:17:01.591', NULL, NULL, NULL, NULL, NULL, 12, NULL);
INSERT INTO bi_billing_item
(item_type, business_type, bo_bookingid, item_source, invoice_id, document_number, od_companyid, od_vendorid, od_customerid, default_fee, billing_item_amount_tcy, billing_item_amount_lcy, billing_item_amount_scy, invoiced_item_amount_tcy, invoiced_item_amount_lcy, invoiced_item_amount_scy, paid_item_amount_tcy, paid_item_amount_lcy, paid_item_amount_scy, currency_code_transaction, currency_code_local, currency_code_system, gd_status, gd_statusflowtype, au_useridins, insertdate, au_useridupd, modifydate, version, dbuserins, dbuserupd, bo_booking_itemid, od_feeid)
VALUES( 'INCOME', 'PLATFORM', 3585, 'TRANSACTION_FEE', NULL, NULL, 553199, NULL, 553123, 0, 6, 6, 6, NULL, NULL, NULL, NULL, NULL, NULL, 'EUR', 'EUR', 'EUR', 'OPEN', 'BILLING_ITEM', 50153, '2020-08-20 14:17:04.181', NULL, NULL, NULL, NULL, NULL, 10, 11);
INSERT INTO bi_billing_item
(item_type, business_type, bo_bookingid, item_source, invoice_id, document_number, od_companyid, od_vendorid, od_customerid, default_fee, billing_item_amount_tcy, billing_item_amount_lcy, billing_item_amount_scy, invoiced_item_amount_tcy, invoiced_item_amount_lcy, invoiced_item_amount_scy, paid_item_amount_tcy, paid_item_amount_lcy, paid_item_amount_scy, currency_code_transaction, currency_code_local, currency_code_system, gd_status, gd_statusflowtype, au_useridins, insertdate, au_useridupd, modifydate, version, dbuserins, dbuserupd, bo_booking_itemid, od_feeid)
VALUES( 'COST', 'PLATFORM', 3585, 'TRANSACTION_FEE', NULL, NULL, 553123, 553199, NULL, 0, 6, 6, 6, NULL, NULL, NULL, NULL, NULL, NULL, 'EUR', 'EUR', 'EUR', 'OPEN', 'BILLING_ITEM', 50153, '2020-08-20 14:17:04.057', NULL, NULL, NULL, NULL, NULL, 10, 11);
INSERT INTO bi_billing_item
(item_type, business_type, bo_bookingid, item_source, invoice_id, document_number, od_companyid, od_vendorid, od_customerid, default_fee, billing_item_amount_tcy, billing_item_amount_lcy, billing_item_amount_scy, invoiced_item_amount_tcy, invoiced_item_amount_lcy, invoiced_item_amount_scy, paid_item_amount_tcy, paid_item_amount_lcy, paid_item_amount_scy, currency_code_transaction, currency_code_local, currency_code_system, gd_status, gd_statusflowtype, au_useridins, insertdate, au_useridupd, modifydate, version, dbuserins, dbuserupd, bo_booking_itemid, od_feeid)
VALUES( 'INCOME', 'PURCHASE_SALE', 3586, 'PRODUCT_RATE', NULL, NULL, 553123, NULL, 553200, NULL, 28, 28, 28, NULL, NULL, NULL, NULL, NULL, NULL, 'EUR', 'EUR', 'EUR', 'OPEN', 'BILLING_ITEM', 50153, '2020-08-25 18:28:58.386', NULL, NULL, NULL, NULL, NULL, 9, NULL);
INSERT INTO bi_billing_item
(item_type, business_type, bo_bookingid, item_source, invoice_id, document_number, od_companyid, od_vendorid, od_customerid, default_fee, billing_item_amount_tcy, billing_item_amount_lcy, billing_item_amount_scy, invoiced_item_amount_tcy, invoiced_item_amount_lcy, invoiced_item_amount_scy, paid_item_amount_tcy, paid_item_amount_lcy, paid_item_amount_scy, currency_code_transaction, currency_code_local, currency_code_system, gd_status, gd_statusflowtype, au_useridins, insertdate, au_useridupd, modifydate, version, dbuserins, dbuserupd, bo_booking_itemid, od_feeid)
VALUES( 'INCOME', 'PLATFORM', 3586, 'TRANSACTION_FEE', NULL, NULL, 553199, NULL, 553123, 0, 6, 6, 6, NULL, NULL, NULL, NULL, NULL, NULL, 'EUR', 'EUR', 'EUR', 'OPEN', 'BILLING_ITEM', 50153, '2020-08-25 18:29:06.349', NULL, NULL, NULL, NULL, NULL, 7, 11);
INSERT INTO bi_billing_item
(item_type, business_type, bo_bookingid, item_source, invoice_id, document_number, od_companyid, od_vendorid, od_customerid, default_fee, billing_item_amount_tcy, billing_item_amount_lcy, billing_item_amount_scy, invoiced_item_amount_tcy, invoiced_item_amount_lcy, invoiced_item_amount_scy, paid_item_amount_tcy, paid_item_amount_lcy, paid_item_amount_scy, currency_code_transaction, currency_code_local, currency_code_system, gd_status, gd_statusflowtype, au_useridins, insertdate, au_useridupd, modifydate, version, dbuserins, dbuserupd, bo_booking_itemid, od_feeid)
VALUES( 'COST', 'PLATFORM', 3586, 'TRANSACTION_FEE', NULL, NULL, 553123, 553199, NULL, 0, 6, 6, 6, NULL, NULL, NULL, NULL, NULL, NULL, 'EUR', 'EUR', 'EUR', 'OPEN', 'BILLING_ITEM', 50153, '2020-08-25 18:29:05.967', NULL, NULL, NULL, NULL, NULL, 7, 11);
INSERT INTO bi_billing_item
(item_type, business_type, bo_bookingid, item_source, invoice_id, document_number, od_companyid, od_vendorid, od_customerid, default_fee, billing_item_amount_tcy, billing_item_amount_lcy, billing_item_amount_scy, invoiced_item_amount_tcy, invoiced_item_amount_lcy, invoiced_item_amount_scy, paid_item_amount_tcy, paid_item_amount_lcy, paid_item_amount_scy, currency_code_transaction, currency_code_local, currency_code_system, gd_status, gd_statusflowtype, au_useridins, insertdate, au_useridupd, modifydate, version, dbuserins, dbuserupd, bo_booking_itemid, od_feeid)
VALUES( 'INCOME', 'PURCHASE_SALE', 3587, 'PRODUCT_RATE', NULL, NULL, 553123, NULL, 553200, NULL, 28, 28, 28, NULL, NULL, NULL, NULL, NULL, NULL, 'EUR', 'EUR', 'EUR', 'OPEN', 'BILLING_ITEM', 50153, '2020-08-25 19:10:03.323', NULL, NULL, NULL, NULL, NULL, 6, NULL);
INSERT INTO bi_billing_item
(item_type, business_type, bo_bookingid, item_source, invoice_id, document_number, od_companyid, od_vendorid, od_customerid, default_fee, billing_item_amount_tcy, billing_item_amount_lcy, billing_item_amount_scy, invoiced_item_amount_tcy, invoiced_item_amount_lcy, invoiced_item_amount_scy, paid_item_amount_tcy, paid_item_amount_lcy, paid_item_amount_scy, currency_code_transaction, currency_code_local, currency_code_system, gd_status, gd_statusflowtype, au_useridins, insertdate, au_useridupd, modifydate, version, dbuserins, dbuserupd, bo_booking_itemid, od_feeid)
VALUES( 'COST', 'PLATFORM', 3587, 'TRANSACTION_FEE', NULL, NULL, 553123, 553199, NULL, 0, 6, 6, 6, NULL, NULL, NULL, NULL, NULL, NULL, 'EUR', 'EUR', 'EUR', 'OPEN', 'BILLING_ITEM', 50153, '2020-08-25 19:10:03.646', NULL, NULL, NULL, NULL, NULL, 4, 11);
INSERT INTO bi_billing_item
(item_type, business_type, bo_bookingid, item_source, invoice_id, document_number, od_companyid, od_vendorid, od_customerid, default_fee, billing_item_amount_tcy, billing_item_amount_lcy, billing_item_amount_scy, invoiced_item_amount_tcy, invoiced_item_amount_lcy, invoiced_item_amount_scy, paid_item_amount_tcy, paid_item_amount_lcy, paid_item_amount_scy, currency_code_transaction, currency_code_local, currency_code_system, gd_status, gd_statusflowtype, au_useridins, insertdate, au_useridupd, modifydate, version, dbuserins, dbuserupd, bo_booking_itemid, od_feeid)
VALUES( 'INCOME', 'PLATFORM', 3587, 'TRANSACTION_FEE', NULL, NULL, 553199, NULL, 553123, 0, 6, 6, 6, NULL, NULL, NULL, NULL, NULL, NULL, 'EUR', 'EUR', 'EUR', 'OPEN', 'BILLING_ITEM', 50153, '2020-08-25 19:09:55.799', NULL, NULL, NULL, NULL, NULL, 4, 11);
INSERT INTO bi_billing_item
(item_type, business_type, bo_bookingid, item_source, invoice_id, document_number, od_companyid, od_vendorid, od_customerid, default_fee, billing_item_amount_tcy, billing_item_amount_lcy, billing_item_amount_scy, invoiced_item_amount_tcy, invoiced_item_amount_lcy, invoiced_item_amount_scy, paid_item_amount_tcy, paid_item_amount_lcy, paid_item_amount_scy, currency_code_transaction, currency_code_local, currency_code_system, gd_status, gd_statusflowtype, au_useridins, insertdate, au_useridupd, modifydate, version, dbuserins, dbuserupd, bo_booking_itemid, od_feeid)
VALUES( 'INCOME', 'PURCHASE_SALE', 3588, 'PRODUCT_RATE', NULL, NULL, 553123, NULL, 553200, NULL, 28, 28, 28, NULL, NULL, NULL, NULL, NULL, NULL, 'EUR', 'EUR', 'EUR', 'OPEN', 'BILLING_ITEM', 50153, '2020-08-25 19:12:41.239', NULL, NULL, NULL, NULL, NULL, 3, NULL);
INSERT INTO bi_billing_item
(item_type, business_type, bo_bookingid, item_source, invoice_id, document_number, od_companyid, od_vendorid, od_customerid, default_fee, billing_item_amount_tcy, billing_item_amount_lcy, billing_item_amount_scy, invoiced_item_amount_tcy, invoiced_item_amount_lcy, invoiced_item_amount_scy, paid_item_amount_tcy, paid_item_amount_lcy, paid_item_amount_scy, currency_code_transaction, currency_code_local, currency_code_system, gd_status, gd_statusflowtype, au_useridins, insertdate, au_useridupd, modifydate, version, dbuserins, dbuserupd, bo_booking_itemid, od_feeid)
VALUES( 'INCOME', 'PLATFORM', 3588, 'TRANSACTION_FEE', NULL, NULL, 553199, NULL, 553123, 0, 6, 6, 6, NULL, NULL, NULL, NULL, NULL, NULL, 'EUR', 'EUR', 'EUR', 'OPEN', 'BILLING_ITEM', 50153, '2020-08-25 19:12:41.547', NULL, NULL, NULL, NULL, NULL, 1, 11);
INSERT INTO bi_billing_item
(item_type, business_type, bo_bookingid, item_source, invoice_id, document_number, od_companyid, od_vendorid, od_customerid, default_fee, billing_item_amount_tcy, billing_item_amount_lcy, billing_item_amount_scy, invoiced_item_amount_tcy, invoiced_item_amount_lcy, invoiced_item_amount_scy, paid_item_amount_tcy, paid_item_amount_lcy, paid_item_amount_scy, currency_code_transaction, currency_code_local, currency_code_system, gd_status, gd_statusflowtype, au_useridins, insertdate, au_useridupd, modifydate, version, dbuserins, dbuserupd, bo_booking_itemid, od_feeid)
VALUES( 'COST', 'PLATFORM', 3588, 'TRANSACTION_FEE', NULL, NULL, 553123, 553199, NULL, 0, 6, 6, 6, NULL, NULL, NULL, NULL, NULL, NULL, 'EUR', 'EUR', 'EUR', 'OPEN', 'BILLING_ITEM', 50153, '2020-08-25 19:12:34.514', NULL, NULL, NULL, NULL, NULL, 1, 11);
